package com.scxd.beans.pojo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.xml.bind.annotation.*;
import java.util.Date;
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties({ "handler","hibernateLazyInitializer" })
@ApiModel(value ="method=sendAlarm")
public class BizAlarmInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.YJXH
     *
     * @mbggenerated
     */
    //@XmlElement(name = "yjxh")
    @ApiModelProperty(value = "预警序号", required = true)
    private String yjxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.HPZL
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "号牌种类")
    private String hpzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.HPHM
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "号牌号码")
    private String hphm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.BKLX
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "布控类型")
    private String bklx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.BKZLX
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "布控子类型")
    private String bkzlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.YJSJ
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "预警时间")
    private Date yjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CLLX
     *
     * @mbggenerated
     */
    private String cllx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CSYS
     *
     * @mbggenerated
     */
   
    private String csys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.GCSJ
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "过车时间")
    private Date gcsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.XSSD
     *
     * @mbggenerated
     */
   
    private Short xssd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.XSQY
     *
     * @mbggenerated
     */
   
    private String xsqy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.XSDD
     *
     * @mbggenerated
     */
   
    private String xsdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.SYXZ
     *
     * @mbggenerated
     */
   
    private String syxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.SBZL
     *
     * @mbggenerated
     */
   
    private String sbzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.SBMC
     *
     * @mbggenerated
     */
   
    private String sbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.JSZZT
     *
     * @mbggenerated
     */
   
    private String jszzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.YWLB
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "业务类别")
    private String ywlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.GCXH
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "过车序号")
    private String gcxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.KKBH
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "卡口编号")
    private String kkbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.KKMC
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "卡口名称")
    private String kkmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.FXLX
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "方向类型")
    private String fxlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CDBH
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "车道编号")
    private String cdbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.QSBM
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "签收部门")
    private String qsbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.ZT
     *
     * @mbggenerated
     */
   
    private String zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.QSSJ
     *
     * @mbggenerated
     */
   
    private Date qssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.FKSJ
     *
     * @mbggenerated
     */
   
    private Date fksj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.YWLX
     *
     * @mbggenerated
     */
    //@XmlElement(name = "ywlx")
    private Short ywlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.QSJG
     *
     * @mbggenerated
     */
    //@XmlElement(name = "qsjg")
    private Short qsjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.SFCJLJ
     *
     * @mbggenerated
     */
    //@XmlElement(name = "sfcjlj")
    private Short sfcjlj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.LJCLQK
     *
     * @mbggenerated
     */
    //@XmlElement(name = "ljclqk")
    private Short ljclqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.WLJDYY
     *
     * @mbggenerated
     */
    //@XmlElement(name = "wljdyy")
    private String wljdyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CHJG
     *
     * @mbggenerated
     */
    //@XmlElement(name = "chjg")
    private Short chjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CLJG
     *
     * @mbggenerated
     */
    //@XmlElement(name = "cljg")
    private String cljg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.WSBH
     *
     * @mbggenerated
     */
    //@XmlElement(name = "wsbh")
    private String wsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.JYW
     *
     * @mbggenerated
     */
    //@XmlElement(name = "jyw")
    private Short jyw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.WSLB
     *
     * @mbggenerated
     */
    //@XmlElement(name = "wslb")
    private Short wslb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CFXYLX
     *
     * @mbggenerated
     */
    //@XmlElement(name = "cfxylx")
    private String cfxylx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CFXYZLX
     *
     * @mbggenerated
     */
    //@XmlElement(name = "cfxyzlx")
    private String cfxyzlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.YJBM
     *
     * @mbggenerated
     */
    //@XmlElement(name = "yjbm")
    private String yjbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.LXR
     *
     * @mbggenerated
     */
    //@XmlElement(name = "lxr")
    private String lxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.LXDH
     *
     * @mbggenerated
     */
    //@XmlElement(name = "lxdh")
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.WCHYY
     *
     * @mbggenerated
     */
    //@XmlElement(name = "wchyy")
    private String wchyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CZQKMS
     *
     * @mbggenerated
     */
    //@XmlElement(name = "czqkms")
    private String czqkms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CZDW
     *
     * @mbggenerated
     */
    //@XmlElement(name = "czdw")
    private String czdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CZR
     *
     * @mbggenerated
     */
    //@XmlElement(name = "czr")
    private String czr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.CZSJ
     *
     * @mbggenerated
     */
    //@XmlElement(name = "czsj")
    private Date czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.TSBJ
     *
     * @mbggenerated
     */
   
    private Short tsbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_ALARM_INFO.QSRY
     *
     * @mbggenerated
     */
   
    private String qsry;

   
    private String ljqkms;

    public String getLjqkms() {
        return ljqkms;
    }

    public void setLjqkms(String ljqkms) {
        this.ljqkms = ljqkms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.YJXH
     *
     * @return the value of BIZ_ALARM_INFO.YJXH
     *
     * @mbggenerated
     */
    public String getYjxh() {
        return yjxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.YJXH
     *
     * @param yjxh the value for BIZ_ALARM_INFO.YJXH
     *
     * @mbggenerated
     */
    public void setYjxh(String yjxh) {
        this.yjxh = yjxh == null ? null : yjxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.HPZL
     *
     * @return the value of BIZ_ALARM_INFO.HPZL
     *
     * @mbggenerated
     */
    public String getHpzl() {
        return hpzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.HPZL
     *
     * @param hpzl the value for BIZ_ALARM_INFO.HPZL
     *
     * @mbggenerated
     */
    public void setHpzl(String hpzl) {
        this.hpzl = hpzl == null ? null : hpzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.HPHM
     *
     * @return the value of BIZ_ALARM_INFO.HPHM
     *
     * @mbggenerated
     */
    public String getHphm() {
        return hphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.HPHM
     *
     * @param hphm the value for BIZ_ALARM_INFO.HPHM
     *
     * @mbggenerated
     */
    public void setHphm(String hphm) {
        this.hphm = hphm == null ? null : hphm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.BKLX
     *
     * @return the value of BIZ_ALARM_INFO.BKLX
     *
     * @mbggenerated
     */
    public String getBklx() {
        return bklx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.BKLX
     *
     * @param bklx the value for BIZ_ALARM_INFO.BKLX
     *
     * @mbggenerated
     */
    public void setBklx(String bklx) {
        this.bklx = bklx == null ? null : bklx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.BKZLX
     *
     * @return the value of BIZ_ALARM_INFO.BKZLX
     *
     * @mbggenerated
     */
    public String getBkzlx() {
        return bkzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.BKZLX
     *
     * @param bkzlx the value for BIZ_ALARM_INFO.BKZLX
     *
     * @mbggenerated
     */
    public void setBkzlx(String bkzlx) {
        this.bkzlx = bkzlx == null ? null : bkzlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.YJSJ
     *
     * @return the value of BIZ_ALARM_INFO.YJSJ
     *
     * @mbggenerated
     */
    public Date getYjsj() {
        return yjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.YJSJ
     *
     * @param yjsj the value for BIZ_ALARM_INFO.YJSJ
     *
     * @mbggenerated
     */
    public void setYjsj(Date yjsj) {
        this.yjsj = yjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CLLX
     *
     * @return the value of BIZ_ALARM_INFO.CLLX
     *
     * @mbggenerated
     */
    public String getCllx() {
        return cllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CLLX
     *
     * @param cllx the value for BIZ_ALARM_INFO.CLLX
     *
     * @mbggenerated
     */
    public void setCllx(String cllx) {
        this.cllx = cllx == null ? null : cllx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CSYS
     *
     * @return the value of BIZ_ALARM_INFO.CSYS
     *
     * @mbggenerated
     */
    public String getCsys() {
        return csys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CSYS
     *
     * @param csys the value for BIZ_ALARM_INFO.CSYS
     *
     * @mbggenerated
     */
    public void setCsys(String csys) {
        this.csys = csys == null ? null : csys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.GCSJ
     *
     * @return the value of BIZ_ALARM_INFO.GCSJ
     *
     * @mbggenerated
     */
    public Date getGcsj() {
        return gcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.GCSJ
     *
     * @param gcsj the value for BIZ_ALARM_INFO.GCSJ
     *
     * @mbggenerated
     */
    public void setGcsj(Date gcsj) {
        this.gcsj = gcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.XSSD
     *
     * @return the value of BIZ_ALARM_INFO.XSSD
     *
     * @mbggenerated
     */
    public Short getXssd() {
        return xssd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.XSSD
     *
     * @param xssd the value for BIZ_ALARM_INFO.XSSD
     *
     * @mbggenerated
     */
    public void setXssd(Short xssd) {
        this.xssd = xssd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.XSQY
     *
     * @return the value of BIZ_ALARM_INFO.XSQY
     *
     * @mbggenerated
     */
    public String getXsqy() {
        return xsqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.XSQY
     *
     * @param xsqy the value for BIZ_ALARM_INFO.XSQY
     *
     * @mbggenerated
     */
    public void setXsqy(String xsqy) {
        this.xsqy = xsqy == null ? null : xsqy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.XSDD
     *
     * @return the value of BIZ_ALARM_INFO.XSDD
     *
     * @mbggenerated
     */
    public String getXsdd() {
        return xsdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.XSDD
     *
     * @param xsdd the value for BIZ_ALARM_INFO.XSDD
     *
     * @mbggenerated
     */
    public void setXsdd(String xsdd) {
        this.xsdd = xsdd == null ? null : xsdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.SYXZ
     *
     * @return the value of BIZ_ALARM_INFO.SYXZ
     *
     * @mbggenerated
     */
    public String getSyxz() {
        return syxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.SYXZ
     *
     * @param syxz the value for BIZ_ALARM_INFO.SYXZ
     *
     * @mbggenerated
     */
    public void setSyxz(String syxz) {
        this.syxz = syxz == null ? null : syxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.SBZL
     *
     * @return the value of BIZ_ALARM_INFO.SBZL
     *
     * @mbggenerated
     */
    public String getSbzl() {
        return sbzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.SBZL
     *
     * @param sbzl the value for BIZ_ALARM_INFO.SBZL
     *
     * @mbggenerated
     */
    public void setSbzl(String sbzl) {
        this.sbzl = sbzl == null ? null : sbzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.SBMC
     *
     * @return the value of BIZ_ALARM_INFO.SBMC
     *
     * @mbggenerated
     */
    public String getSbmc() {
        return sbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.SBMC
     *
     * @param sbmc the value for BIZ_ALARM_INFO.SBMC
     *
     * @mbggenerated
     */
    public void setSbmc(String sbmc) {
        this.sbmc = sbmc == null ? null : sbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.JSZZT
     *
     * @return the value of BIZ_ALARM_INFO.JSZZT
     *
     * @mbggenerated
     */
    public String getJszzt() {
        return jszzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.JSZZT
     *
     * @param jszzt the value for BIZ_ALARM_INFO.JSZZT
     *
     * @mbggenerated
     */
    public void setJszzt(String jszzt) {
        this.jszzt = jszzt == null ? null : jszzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.YWLB
     *
     * @return the value of BIZ_ALARM_INFO.YWLB
     *
     * @mbggenerated
     */
    public String getYwlb() {
        return ywlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.YWLB
     *
     * @param ywlb the value for BIZ_ALARM_INFO.YWLB
     *
     * @mbggenerated
     */
    public void setYwlb(String ywlb) {
        this.ywlb = ywlb == null ? null : ywlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.GCXH
     *
     * @return the value of BIZ_ALARM_INFO.GCXH
     *
     * @mbggenerated
     */
    public String getGcxh() {
        return gcxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.GCXH
     *
     * @param gcxh the value for BIZ_ALARM_INFO.GCXH
     *
     * @mbggenerated
     */
    public void setGcxh(String gcxh) {
        this.gcxh = gcxh == null ? null : gcxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.KKBH
     *
     * @return the value of BIZ_ALARM_INFO.KKBH
     *
     * @mbggenerated
     */
    public String getKkbh() {
        return kkbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.KKBH
     *
     * @param kkbh the value for BIZ_ALARM_INFO.KKBH
     *
     * @mbggenerated
     */
    public void setKkbh(String kkbh) {
        this.kkbh = kkbh == null ? null : kkbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.KKMC
     *
     * @return the value of BIZ_ALARM_INFO.KKMC
     *
     * @mbggenerated
     */
    public String getKkmc() {
        return kkmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.KKMC
     *
     * @param kkmc the value for BIZ_ALARM_INFO.KKMC
     *
     * @mbggenerated
     */
    public void setKkmc(String kkmc) {
        this.kkmc = kkmc == null ? null : kkmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.FXLX
     *
     * @return the value of BIZ_ALARM_INFO.FXLX
     *
     * @mbggenerated
     */
    public String getFxlx() {
        return fxlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.FXLX
     *
     * @param fxlx the value for BIZ_ALARM_INFO.FXLX
     *
     * @mbggenerated
     */
    public void setFxlx(String fxlx) {
        this.fxlx = fxlx == null ? null : fxlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CDBH
     *
     * @return the value of BIZ_ALARM_INFO.CDBH
     *
     * @mbggenerated
     */
    public String getCdbh() {
        return cdbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CDBH
     *
     * @param cdbh the value for BIZ_ALARM_INFO.CDBH
     *
     * @mbggenerated
     */
    public void setCdbh(String cdbh) {
        this.cdbh = cdbh == null ? null : cdbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.QSBM
     *
     * @return the value of BIZ_ALARM_INFO.QSBM
     *
     * @mbggenerated
     */
    public String getQsbm() {
        return qsbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.QSBM
     *
     * @param qsbm the value for BIZ_ALARM_INFO.QSBM
     *
     * @mbggenerated
     */
    public void setQsbm(String qsbm) {
        this.qsbm = qsbm == null ? null : qsbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.ZT
     *
     * @return the value of BIZ_ALARM_INFO.ZT
     *
     * @mbggenerated
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.ZT
     *
     * @param zt the value for BIZ_ALARM_INFO.ZT
     *
     * @mbggenerated
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.QSSJ
     *
     * @return the value of BIZ_ALARM_INFO.QSSJ
     *
     * @mbggenerated
     */
    public Date getQssj() {
        return qssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.QSSJ
     *
     * @param qssj the value for BIZ_ALARM_INFO.QSSJ
     *
     * @mbggenerated
     */
    public void setQssj(Date qssj) {
        this.qssj = qssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.FKSJ
     *
     * @return the value of BIZ_ALARM_INFO.FKSJ
     *
     * @mbggenerated
     */
    public Date getFksj() {
        return fksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.FKSJ
     *
     * @param fksj the value for BIZ_ALARM_INFO.FKSJ
     *
     * @mbggenerated
     */
    public void setFksj(Date fksj) {
        this.fksj = fksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.YWLX
     *
     * @return the value of BIZ_ALARM_INFO.YWLX
     *
     * @mbggenerated
     */
    public Short getYwlx() {
        return ywlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.YWLX
     *
     * @param ywlx the value for BIZ_ALARM_INFO.YWLX
     *
     * @mbggenerated
     */
    public void setYwlx(Short ywlx) {
        this.ywlx = ywlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.QSJG
     *
     * @return the value of BIZ_ALARM_INFO.QSJG
     *
     * @mbggenerated
     */
    public Short getQsjg() {
        return qsjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.QSJG
     *
     * @param qsjg the value for BIZ_ALARM_INFO.QSJG
     *
     * @mbggenerated
     */
    public void setQsjg(Short qsjg) {
        this.qsjg = qsjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.SFCJLJ
     *
     * @return the value of BIZ_ALARM_INFO.SFCJLJ
     *
     * @mbggenerated
     */
    public Short getSfcjlj() {
        return sfcjlj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.SFCJLJ
     *
     * @param sfcjlj the value for BIZ_ALARM_INFO.SFCJLJ
     *
     * @mbggenerated
     */
    public void setSfcjlj(Short sfcjlj) {
        this.sfcjlj = sfcjlj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.LJCLQK
     *
     * @return the value of BIZ_ALARM_INFO.LJCLQK
     *
     * @mbggenerated
     */
    public Short getLjclqk() {
        return ljclqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.LJCLQK
     *
     * @param ljclqk the value for BIZ_ALARM_INFO.LJCLQK
     *
     * @mbggenerated
     */
    public void setLjclqk(Short ljclqk) {
        this.ljclqk = ljclqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.WLJDYY
     *
     * @return the value of BIZ_ALARM_INFO.WLJDYY
     *
     * @mbggenerated
     */
    public String getWljdyy() {
        return wljdyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.WLJDYY
     *
     * @param wljdyy the value for BIZ_ALARM_INFO.WLJDYY
     *
     * @mbggenerated
     */
    public void setWljdyy(String wljdyy) {
        this.wljdyy = wljdyy == null ? null : wljdyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CHJG
     *
     * @return the value of BIZ_ALARM_INFO.CHJG
     *
     * @mbggenerated
     */
    public Short getChjg() {
        return chjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CHJG
     *
     * @param chjg the value for BIZ_ALARM_INFO.CHJG
     *
     * @mbggenerated
     */
    public void setChjg(Short chjg) {
        this.chjg = chjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CLJG
     *
     * @return the value of BIZ_ALARM_INFO.CLJG
     *
     * @mbggenerated
     */
    public String getCljg() {
        return cljg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CLJG
     *
     * @param cljg the value for BIZ_ALARM_INFO.CLJG
     *
     * @mbggenerated
     */
    public void setCljg(String cljg) {
        this.cljg = cljg == null ? null : cljg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.WSBH
     *
     * @return the value of BIZ_ALARM_INFO.WSBH
     *
     * @mbggenerated
     */
    public String getWsbh() {
        return wsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.WSBH
     *
     * @param wsbh the value for BIZ_ALARM_INFO.WSBH
     *
     * @mbggenerated
     */
    public void setWsbh(String wsbh) {
        this.wsbh = wsbh == null ? null : wsbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.JYW
     *
     * @return the value of BIZ_ALARM_INFO.JYW
     *
     * @mbggenerated
     */
    public Short getJyw() {
        return jyw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.JYW
     *
     * @param jyw the value for BIZ_ALARM_INFO.JYW
     *
     * @mbggenerated
     */
    public void setJyw(Short jyw) {
        this.jyw = jyw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.WSLB
     *
     * @return the value of BIZ_ALARM_INFO.WSLB
     *
     * @mbggenerated
     */
    public Short getWslb() {
        return wslb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.WSLB
     *
     * @param wslb the value for BIZ_ALARM_INFO.WSLB
     *
     * @mbggenerated
     */
    public void setWslb(Short wslb) {
        this.wslb = wslb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CFXYLX
     *
     * @return the value of BIZ_ALARM_INFO.CFXYLX
     *
     * @mbggenerated
     */
    public String getCfxylx() {
        return cfxylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CFXYLX
     *
     * @param cfxylx the value for BIZ_ALARM_INFO.CFXYLX
     *
     * @mbggenerated
     */
    public void setCfxylx(String cfxylx) {
        this.cfxylx = cfxylx == null ? null : cfxylx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CFXYZLX
     *
     * @return the value of BIZ_ALARM_INFO.CFXYZLX
     *
     * @mbggenerated
     */
    public String getCfxyzlx() {
        return cfxyzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CFXYZLX
     *
     * @param cfxyzlx the value for BIZ_ALARM_INFO.CFXYZLX
     *
     * @mbggenerated
     */
    public void setCfxyzlx(String cfxyzlx) {
        this.cfxyzlx = cfxyzlx == null ? null : cfxyzlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.YJBM
     *
     * @return the value of BIZ_ALARM_INFO.YJBM
     *
     * @mbggenerated
     */
    public String getYjbm() {
        return yjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.YJBM
     *
     * @param yjbm the value for BIZ_ALARM_INFO.YJBM
     *
     * @mbggenerated
     */
    public void setYjbm(String yjbm) {
        this.yjbm = yjbm == null ? null : yjbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.LXR
     *
     * @return the value of BIZ_ALARM_INFO.LXR
     *
     * @mbggenerated
     */
    public String getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.LXR
     *
     * @param lxr the value for BIZ_ALARM_INFO.LXR
     *
     * @mbggenerated
     */
    public void setLxr(String lxr) {
        this.lxr = lxr == null ? null : lxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.LXDH
     *
     * @return the value of BIZ_ALARM_INFO.LXDH
     *
     * @mbggenerated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.LXDH
     *
     * @param lxdh the value for BIZ_ALARM_INFO.LXDH
     *
     * @mbggenerated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.WCHYY
     *
     * @return the value of BIZ_ALARM_INFO.WCHYY
     *
     * @mbggenerated
     */
    public String getWchyy() {
        return wchyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.WCHYY
     *
     * @param wchyy the value for BIZ_ALARM_INFO.WCHYY
     *
     * @mbggenerated
     */
    public void setWchyy(String wchyy) {
        this.wchyy = wchyy == null ? null : wchyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CZQKMS
     *
     * @return the value of BIZ_ALARM_INFO.CZQKMS
     *
     * @mbggenerated
     */
    public String getCzqkms() {
        return czqkms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CZQKMS
     *
     * @param czqkms the value for BIZ_ALARM_INFO.CZQKMS
     *
     * @mbggenerated
     */
    public void setCzqkms(String czqkms) {
        this.czqkms = czqkms == null ? null : czqkms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CZDW
     *
     * @return the value of BIZ_ALARM_INFO.CZDW
     *
     * @mbggenerated
     */
    public String getCzdw() {
        return czdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CZDW
     *
     * @param czdw the value for BIZ_ALARM_INFO.CZDW
     *
     * @mbggenerated
     */
    public void setCzdw(String czdw) {
        this.czdw = czdw == null ? null : czdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CZR
     *
     * @return the value of BIZ_ALARM_INFO.CZR
     *
     * @mbggenerated
     */
    public String getCzr() {
        return czr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CZR
     *
     * @param czr the value for BIZ_ALARM_INFO.CZR
     *
     * @mbggenerated
     */
    public void setCzr(String czr) {
        this.czr = czr == null ? null : czr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.CZSJ
     *
     * @return the value of BIZ_ALARM_INFO.CZSJ
     *
     * @mbggenerated
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.CZSJ
     *
     * @param czsj the value for BIZ_ALARM_INFO.CZSJ
     *
     * @mbggenerated
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.TSBJ
     *
     * @return the value of BIZ_ALARM_INFO.TSBJ
     *
     * @mbggenerated
     */
    public Short getTsbj() {
        return tsbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.TSBJ
     *
     * @param tsbj the value for BIZ_ALARM_INFO.TSBJ
     *
     * @mbggenerated
     */
    public void setTsbj(Short tsbj) {
        this.tsbj = tsbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ALARM_INFO.QSRY
     *
     * @return the value of BIZ_ALARM_INFO.QSRY
     *
     * @mbggenerated
     */
    public String getQsry() {
        return qsry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ALARM_INFO.QSRY
     *
     * @param qsry the value for BIZ_ALARM_INFO.QSRY
     *
     * @mbggenerated
     */
    public void setQsry(String qsry) {
        this.qsry = qsry == null ? null : qsry.trim();
    }
}