package com.scxd.beans.pojo;

import java.util.UUID;

public class BizPoliceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_POLICE_INFO.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_POLICE_INFO.RYLX
     *
     * @mbggenerated
     */
    private String rylx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_POLICE_INFO.XM
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_POLICE_INFO.RYBH
     *
     * @mbggenerated
     */
    private String rybh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_POLICE_INFO.SFZMHM
     *
     * @mbggenerated
     */
    private String sfzmhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_POLICE_INFO.SJHM
     *
     * @mbggenerated
     */
    private String sjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_POLICE_INFO.BMDM
     *
     * @mbggenerated
     */
    private String bmdm;

    private String  fwzbh;
    private  int ly=1;

    public String getFwzbh() {
        return fwzbh;
    }

    public void setFwzbh(String fwzbh) {
        this.fwzbh = fwzbh;
    }

    public int getLy() {
        return ly;
    }

    public void setLy(int ly) {
        this.ly = ly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_POLICE_INFO.ID
     *
     * @return the value of BIZ_POLICE_INFO.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_POLICE_INFO.ID
     *
     * @param id the value for BIZ_POLICE_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_POLICE_INFO.RYLX
     *
     * @return the value of BIZ_POLICE_INFO.RYLX
     *
     * @mbggenerated
     */
    public String getRylx() {
        return rylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_POLICE_INFO.RYLX
     *
     * @param rylx the value for BIZ_POLICE_INFO.RYLX
     *
     * @mbggenerated
     */
    public void setRylx(String rylx) {
        this.rylx = rylx == null ? null : rylx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_POLICE_INFO.XM
     *
     * @return the value of BIZ_POLICE_INFO.XM
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_POLICE_INFO.XM
     *
     * @param xm the value for BIZ_POLICE_INFO.XM
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_POLICE_INFO.RYBH
     *
     * @return the value of BIZ_POLICE_INFO.RYBH
     *
     * @mbggenerated
     */
    public String getRybh() {
        return rybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_POLICE_INFO.RYBH
     *
     * @param rybh the value for BIZ_POLICE_INFO.RYBH
     *
     * @mbggenerated
     */
    public void setRybh(String rybh) {
        this.rybh = rybh == null ? null : rybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_POLICE_INFO.SFZMHM
     *
     * @return the value of BIZ_POLICE_INFO.SFZMHM
     *
     * @mbggenerated
     */
    public String getSfzmhm() {
        return sfzmhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_POLICE_INFO.SFZMHM
     *
     * @param sfzmhm the value for BIZ_POLICE_INFO.SFZMHM
     *
     * @mbggenerated
     */
    public void setSfzmhm(String sfzmhm) {
        this.sfzmhm = sfzmhm == null ? null : sfzmhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_POLICE_INFO.SJHM
     *
     * @return the value of BIZ_POLICE_INFO.SJHM
     *
     * @mbggenerated
     */
    public String getSjhm() {
        return sjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_POLICE_INFO.SJHM
     *
     * @param sjhm the value for BIZ_POLICE_INFO.SJHM
     *
     * @mbggenerated
     */
    public void setSjhm(String sjhm) {
        this.sjhm = sjhm == null ? null : sjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_POLICE_INFO.BMDM
     *
     * @return the value of BIZ_POLICE_INFO.BMDM
     *
     * @mbggenerated
     */
    public String getBmdm() {
        return bmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_POLICE_INFO.BMDM
     *
     * @param bmdm the value for BIZ_POLICE_INFO.BMDM
     *
     * @mbggenerated
     */
    public void setBmdm(String bmdm) {
        this.bmdm = bmdm == null ? null : bmdm.trim();
    }
}