package com.scxd.beans.pojo;

import java.util.Date;
import java.util.List;

public class BizRmConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_RM_CONFIG.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_RM_CONFIG.BMBH
     *
     * @mbggenerated
     */
    private String bmbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_RM_CONFIG.CJSJ
     *
     * @mbggenerated
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_RM_CONFIG.CJR
     *
     * @mbggenerated
     */
    private String cjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_RM_CONFIG.TSZT
     *
     * @mbggenerated
     */
    private Short tszt;

    private List<BizRmConfigDetail> bizRmConfigDetails;

    public List<BizRmConfigDetail> getBizRmConfigDetails() {
        return bizRmConfigDetails;
    }

    public void setBizRmConfigDetails(List<BizRmConfigDetail> bizRmConfigDetails) {
        this.bizRmConfigDetails = bizRmConfigDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_RM_CONFIG.ID
     *
     * @return the value of BIZ_RM_CONFIG.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_RM_CONFIG.ID
     *
     * @param id the value for BIZ_RM_CONFIG.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_RM_CONFIG.BMBH
     *
     * @return the value of BIZ_RM_CONFIG.BMBH
     *
     * @mbggenerated
     */
    public String getBmbh() {
        return bmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_RM_CONFIG.BMBH
     *
     * @param bmbh the value for BIZ_RM_CONFIG.BMBH
     *
     * @mbggenerated
     */
    public void setBmbh(String bmbh) {
        this.bmbh = bmbh == null ? null : bmbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_RM_CONFIG.CJSJ
     *
     * @return the value of BIZ_RM_CONFIG.CJSJ
     *
     * @mbggenerated
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_RM_CONFIG.CJSJ
     *
     * @param cjsj the value for BIZ_RM_CONFIG.CJSJ
     *
     * @mbggenerated
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_RM_CONFIG.CJR
     *
     * @return the value of BIZ_RM_CONFIG.CJR
     *
     * @mbggenerated
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_RM_CONFIG.CJR
     *
     * @param cjr the value for BIZ_RM_CONFIG.CJR
     *
     * @mbggenerated
     */
    public void setCjr(String cjr) {
        this.cjr = cjr == null ? null : cjr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_RM_CONFIG.TSZT
     *
     * @return the value of BIZ_RM_CONFIG.TSZT
     *
     * @mbggenerated
     */
    public Short getTszt() {
        return tszt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_RM_CONFIG.TSZT
     *
     * @param tszt the value for BIZ_RM_CONFIG.TSZT
     *
     * @mbggenerated
     */
    public void setTszt(Short tszt) {
        this.tszt = tszt;
    }
}