package com.scxd.beans.pojo;

public class BizRoadBlocks {

    private String id = "";

    private String kkbh = "";

    private String fxlx = "";

    private String sxfxlxmc = "";

    private String xxfxlxmc = "";

    private String kkmc = "";

    private String kklx = "";

    private String kklxmc = "";

    private Short kkxz;

    private String kkxzmc = "";

    private String glbm = "";

    private String xzqh = "";

    private String xzqhmc = "";

    private String sjxzqh = "";

    private String dldm = "";

    private String dlmc = "";

    private String dllx = "";

    private String dllxmc = "";

    private String lkh = "";

    private String dlms = "";

    private String kkjd = "";

    private String kkwd = "";

    private Short ljtj;

    private  String zfzbh = "";

    private int ly;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.ID
     *
     * @return the value of BIZ_ROAD_BLOCKS.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.ID
     *
     * @param id the value for BIZ_ROAD_BLOCKS.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getZfzbh() {
        return zfzbh;
    }

    public void setZfzbh(String zfzbh) {
        this.zfzbh = zfzbh;
    }

    public int getLy() {
        return ly;
    }

    public void setLy(int ly) {
        this.ly = ly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.KKBH
     *
     * @return the value of BIZ_ROAD_BLOCKS.KKBH
     *
     * @mbggenerated
     */
    public String getKkbh() {
        return kkbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.KKBH
     *
     * @param kkbh the value for BIZ_ROAD_BLOCKS.KKBH
     *
     * @mbggenerated
     */
    public void setKkbh(String kkbh) {
        this.kkbh = kkbh == null ? null : kkbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.FXLX
     *
     * @return the value of BIZ_ROAD_BLOCKS.FXLX
     *
     * @mbggenerated
     */
    public String getFxlx() {
        return fxlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.FXLX
     *
     * @param fxlx the value for BIZ_ROAD_BLOCKS.FXLX
     *
     * @mbggenerated
     */
    public void setFxlx(String fxlx) {
        this.fxlx = fxlx == null ? null : fxlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.SXFXLXMC
     *
     * @return the value of BIZ_ROAD_BLOCKS.SXFXLXMC
     *
     * @mbggenerated
     */
    public String getSxfxlxmc() {
        return sxfxlxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.SXFXLXMC
     *
     * @param sxfxlxmc the value for BIZ_ROAD_BLOCKS.SXFXLXMC
     *
     * @mbggenerated
     */
    public void setSxfxlxmc(String sxfxlxmc) {
        this.sxfxlxmc = sxfxlxmc == null ? null : sxfxlxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.XXFXLXMC
     *
     * @return the value of BIZ_ROAD_BLOCKS.XXFXLXMC
     *
     * @mbggenerated
     */
    public String getXxfxlxmc() {
        return xxfxlxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.XXFXLXMC
     *
     * @param xxfxlxmc the value for BIZ_ROAD_BLOCKS.XXFXLXMC
     *
     * @mbggenerated
     */
    public void setXxfxlxmc(String xxfxlxmc) {
        this.xxfxlxmc = xxfxlxmc == null ? null : xxfxlxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.KKMC
     *
     * @return the value of BIZ_ROAD_BLOCKS.KKMC
     *
     * @mbggenerated
     */
    public String getKkmc() {
        return kkmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.KKMC
     *
     * @param kkmc the value for BIZ_ROAD_BLOCKS.KKMC
     *
     * @mbggenerated
     */
    public void setKkmc(String kkmc) {
        this.kkmc = kkmc == null ? null : kkmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.KKLX
     *
     * @return the value of BIZ_ROAD_BLOCKS.KKLX
     *
     * @mbggenerated
     */
    public String getKklx() {
        return kklx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.KKLX
     *
     * @param kklx the value for BIZ_ROAD_BLOCKS.KKLX
     *
     * @mbggenerated
     */
    public void setKklx(String kklx) {
        this.kklx = kklx == null ? null : kklx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.KKLXMC
     *
     * @return the value of BIZ_ROAD_BLOCKS.KKLXMC
     *
     * @mbggenerated
     */
    public String getKklxmc() {
        return kklxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.KKLXMC
     *
     * @param kklxmc the value for BIZ_ROAD_BLOCKS.KKLXMC
     *
     * @mbggenerated
     */
    public void setKklxmc(String kklxmc) {
        this.kklxmc = kklxmc == null ? null : kklxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.KKXZ
     *
     * @return the value of BIZ_ROAD_BLOCKS.KKXZ
     *
     * @mbggenerated
     */
    public Short getKkxz() {
        return kkxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.KKXZ
     *
     * @param kkxz the value for BIZ_ROAD_BLOCKS.KKXZ
     *
     * @mbggenerated
     */
    public void setKkxz(Short kkxz) {
        this.kkxz = kkxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.KKXZMC
     *
     * @return the value of BIZ_ROAD_BLOCKS.KKXZMC
     *
     * @mbggenerated
     */
    public String getKkxzmc() {
        return kkxzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.KKXZMC
     *
     * @param kkxzmc the value for BIZ_ROAD_BLOCKS.KKXZMC
     *
     * @mbggenerated
     */
    public void setKkxzmc(String kkxzmc) {
        this.kkxzmc = kkxzmc == null ? null : kkxzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.GLBM
     *
     * @return the value of BIZ_ROAD_BLOCKS.GLBM
     *
     * @mbggenerated
     */
    public String getGlbm() {
        return glbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.GLBM
     *
     * @param glbm the value for BIZ_ROAD_BLOCKS.GLBM
     *
     * @mbggenerated
     */
    public void setGlbm(String glbm) {
        this.glbm = glbm == null ? null : glbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.XZQH
     *
     * @return the value of BIZ_ROAD_BLOCKS.XZQH
     *
     * @mbggenerated
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.XZQH
     *
     * @param xzqh the value for BIZ_ROAD_BLOCKS.XZQH
     *
     * @mbggenerated
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh == null ? null : xzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.XZQHMC
     *
     * @return the value of BIZ_ROAD_BLOCKS.XZQHMC
     *
     * @mbggenerated
     */
    public String getXzqhmc() {
        return xzqhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.XZQHMC
     *
     * @param xzqhmc the value for BIZ_ROAD_BLOCKS.XZQHMC
     *
     * @mbggenerated
     */
    public void setXzqhmc(String xzqhmc) {
        this.xzqhmc = xzqhmc == null ? null : xzqhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.SJXZQH
     *
     * @return the value of BIZ_ROAD_BLOCKS.SJXZQH
     *
     * @mbggenerated
     */
    public String getSjxzqh() {
        return sjxzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.SJXZQH
     *
     * @param sjxzqh the value for BIZ_ROAD_BLOCKS.SJXZQH
     *
     * @mbggenerated
     */
    public void setSjxzqh(String sjxzqh) {
        this.sjxzqh = sjxzqh == null ? null : sjxzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.DLDM
     *
     * @return the value of BIZ_ROAD_BLOCKS.DLDM
     *
     * @mbggenerated
     */
    public String getDldm() {
        return dldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.DLDM
     *
     * @param dldm the value for BIZ_ROAD_BLOCKS.DLDM
     *
     * @mbggenerated
     */
    public void setDldm(String dldm) {
        this.dldm = dldm == null ? null : dldm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.DLMC
     *
     * @return the value of BIZ_ROAD_BLOCKS.DLMC
     *
     * @mbggenerated
     */
    public String getDlmc() {
        return dlmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.DLMC
     *
     * @param dlmc the value for BIZ_ROAD_BLOCKS.DLMC
     *
     * @mbggenerated
     */
    public void setDlmc(String dlmc) {
        this.dlmc = dlmc == null ? null : dlmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.DLLX
     *
     * @return the value of BIZ_ROAD_BLOCKS.DLLX
     *
     * @mbggenerated
     */
    public String getDllx() {
        return dllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.DLLX
     *
     * @param dllx the value for BIZ_ROAD_BLOCKS.DLLX
     *
     * @mbggenerated
     */
    public void setDllx(String dllx) {
        this.dllx = dllx == null ? null : dllx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.DLLXMC
     *
     * @return the value of BIZ_ROAD_BLOCKS.DLLXMC
     *
     * @mbggenerated
     */
    public String getDllxmc() {
        return dllxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.DLLXMC
     *
     * @param dllxmc the value for BIZ_ROAD_BLOCKS.DLLXMC
     *
     * @mbggenerated
     */
    public void setDllxmc(String dllxmc) {
        this.dllxmc = dllxmc == null ? null : dllxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.LKH
     *
     * @return the value of BIZ_ROAD_BLOCKS.LKH
     *
     * @mbggenerated
     */
    public String getLkh() {
        return lkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.LKH
     *
     * @param lkh the value for BIZ_ROAD_BLOCKS.LKH
     *
     * @mbggenerated
     */
    public void setLkh(String lkh) {
        this.lkh = lkh == null ? null : lkh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.DLMS
     *
     * @return the value of BIZ_ROAD_BLOCKS.DLMS
     *
     * @mbggenerated
     */
    public String getDlms() {
        return dlms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.DLMS
     *
     * @param dlms the value for BIZ_ROAD_BLOCKS.DLMS
     *
     * @mbggenerated
     */
    public void setDlms(String dlms) {
        this.dlms = dlms == null ? null : dlms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.KKJD
     *
     * @return the value of BIZ_ROAD_BLOCKS.KKJD
     *
     * @mbggenerated
     */
    public String getKkjd() {
        return kkjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.KKJD
     *
     * @param kkjd the value for BIZ_ROAD_BLOCKS.KKJD
     *
     * @mbggenerated
     */
    public void setKkjd(String kkjd) {
        this.kkjd = kkjd == null ? null : kkjd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.KKWD
     *
     * @return the value of BIZ_ROAD_BLOCKS.KKWD
     *
     * @mbggenerated
     */
    public String getKkwd() {
        return kkwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.KKWD
     *
     * @param kkwd the value for BIZ_ROAD_BLOCKS.KKWD
     *
     * @mbggenerated
     */
    public void setKkwd(String kkwd) {
        this.kkwd = kkwd == null ? null : kkwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_ROAD_BLOCKS.LJTJ
     *
     * @return the value of BIZ_ROAD_BLOCKS.LJTJ
     *
     * @mbggenerated
     */
    public Short getLjtj() {
        return ljtj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_ROAD_BLOCKS.LJTJ
     *
     * @param ljtj the value for BIZ_ROAD_BLOCKS.LJTJ
     *
     * @mbggenerated
     */
    public void setLjtj(Short ljtj) {
        this.ljtj = ljtj;
    }
}