package com.scxd.beans.pojo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.scxd.common.CustomDateSerializer;
import com.scxd.common.CustomJsonDateDeserializer;

import java.util.Date;
@JsonIgnoreProperties(ignoreUnknown = true)
public class BizVioForce {

    private String wfnr;

    public String getWfnr() {
        return wfnr;
    }

    public void setWfnr(String wfnr) {
        this.wfnr = wfnr;
    }

    private String id = "";

    private String pzbh  = "";

    private String wslb  = "";

    private String qzcslx  = "";

    private String klwpcfd  = "";

    private String sjxm  = "";

    private String sjwpmc  = "";

    private String sjwpcfd  = "";

    private String ryfl  = "";

    private String jszh  = "";

    private String dabh  = "";

    private String fzjg  = "";

    private String zjcx  = "";

    private String dsr  = "";
    private String lxdz;

    public String getLxdz() {
        return lxdz;
    }

    public void setLxdz(String lxdz) {
        this.lxdz = lxdz;
    }

    private String zsxzqh  = "";

    private String zsxxdz  = "";

    private String dh  = "";

    private String lxfs  = "";

    private String clfl  = "";

    private String hpzl  = "";

    private String hphm  = "";

    private String jdcsyr  = "";

    private String fdjh  = "";

    private String clsbdh  = "";

    private String syxz  = "";

    private String jtfs  = "";

    private Date wfsj;

    private String xzqh  = "";

    private String wfdd  = "";

    private String lddm  = "";

    private String ddms  = "";

    private String wfdz  = "";

    private String wfxw1  = "";

    private String scz1  = "";

    private String bzz1  = "";

    private String wfxw2  = "";

    private String scz2  = "";

    private String bzz2  = "";

    private String wfxw3;

    private String scz3;

    private String bzz3;

    private String wfxw4;

    private String scz4;

    private String bzz4;

    private String wfxw5;

    private String scz5;

    private String bzz5;

    private String zqmj  = "";

    private String fxjg  = "";

    private String jsjqbj  = "";

    private String sgdj  = "";

    private String mjyj  = "";

    private String jd  = "";

    private String wd  = "";

    private String gls  = "";

    private String flyj  = "";

    private String dsryy  = "";

   private String hpzlname ="";

   private String lrrname = "";

    private String xzssjg = "";

    private String bz  = "";

    private Short dybj;

    private Short dycs;

    private String lrr  = "";

    public String getXzssjg() {
        return xzssjg;
    }

    public void setXzssjg(String xzssjg) {
        this.xzssjg = xzssjg;
    }

    public String getLrr() {
        return lrr;
    }

    public void setLrr(String lrr) {
        this.lrr = lrr;
    }

    public String getHpzlname() {
        return hpzlname;
    }

    public void setHpzlname(String hpzlname) {
        this.hpzlname = hpzlname;
    }

    public String getLrrname() {
        return lrrname;
    }

    public void setLrrname(String lrrname) {
        this.lrrname = lrrname;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.PZBH
     *
     * @return the value of BIZ_VIO_FORCE.PZBH
     *
     * @mbggenerated
     */
    public String getPzbh() {
        return pzbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.PZBH
     *
     * @param pzbh the value for BIZ_VIO_FORCE.PZBH
     *
     * @mbggenerated
     */
    public void setPzbh(String pzbh) {
        this.pzbh = pzbh == null ? null : pzbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.WSLB
     *
     * @return the value of BIZ_VIO_FORCE.WSLB
     *
     * @mbggenerated
     */
    public String getWslb() {
        return wslb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.WSLB
     *
     * @param wslb the value for BIZ_VIO_FORCE.WSLB
     *
     * @mbggenerated
     */
    public void setWslb(String wslb) {
        this.wslb = wslb == null ? null : wslb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.QZCSLX
     *
     * @return the value of BIZ_VIO_FORCE.QZCSLX
     *
     * @mbggenerated
     */
    public String getQzcslx() {
        return qzcslx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.QZCSLX
     *
     * @param qzcslx the value for BIZ_VIO_FORCE.QZCSLX
     *
     * @mbggenerated
     */
    public void setQzcslx(String qzcslx) {
        this.qzcslx = qzcslx == null ? null : qzcslx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.KLWPCFD
     *
     * @return the value of BIZ_VIO_FORCE.KLWPCFD
     *
     * @mbggenerated
     */
    public String getKlwpcfd() {
        return klwpcfd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.KLWPCFD
     *
     * @param klwpcfd the value for BIZ_VIO_FORCE.KLWPCFD
     *
     * @mbggenerated
     */
    public void setKlwpcfd(String klwpcfd) {
        this.klwpcfd = klwpcfd == null ? null : klwpcfd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.SJXM
     *
     * @return the value of BIZ_VIO_FORCE.SJXM
     *
     * @mbggenerated
     */
    public String getSjxm() {
        return sjxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.SJXM
     *
     * @param sjxm the value for BIZ_VIO_FORCE.SJXM
     *
     * @mbggenerated
     */
    public void setSjxm(String sjxm) {
        this.sjxm = sjxm == null ? null : sjxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.SJWPMC
     *
     * @return the value of BIZ_VIO_FORCE.SJWPMC
     *
     * @mbggenerated
     */
    public String getSjwpmc() {
        return sjwpmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.SJWPMC
     *
     * @param sjwpmc the value for BIZ_VIO_FORCE.SJWPMC
     *
     * @mbggenerated
     */
    public void setSjwpmc(String sjwpmc) {
        this.sjwpmc = sjwpmc == null ? null : sjwpmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.SJWPCFD
     *
     * @return the value of BIZ_VIO_FORCE.SJWPCFD
     *
     * @mbggenerated
     */
    public String getSjwpcfd() {
        return sjwpcfd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.SJWPCFD
     *
     * @param sjwpcfd the value for BIZ_VIO_FORCE.SJWPCFD
     *
     * @mbggenerated
     */
    public void setSjwpcfd(String sjwpcfd) {
        this.sjwpcfd = sjwpcfd == null ? null : sjwpcfd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.RYFL
     *
     * @return the value of BIZ_VIO_FORCE.RYFL
     *
     * @mbggenerated
     */
    public String getRyfl() {
        return ryfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.RYFL
     *
     * @param ryfl the value for BIZ_VIO_FORCE.RYFL
     *
     * @mbggenerated
     */
    public void setRyfl(String ryfl) {
        this.ryfl = ryfl == null ? null : ryfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.JSZH
     *
     * @return the value of BIZ_VIO_FORCE.JSZH
     *
     * @mbggenerated
     */
    public String getJszh() {
        return jszh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.JSZH
     *
     * @param jszh the value for BIZ_VIO_FORCE.JSZH
     *
     * @mbggenerated
     */
    public void setJszh(String jszh) {
        this.jszh = jszh == null ? null : jszh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.DABH
     *
     * @return the value of BIZ_VIO_FORCE.DABH
     *
     * @mbggenerated
     */
    public String getDabh() {
        return dabh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.DABH
     *
     * @param dabh the value for BIZ_VIO_FORCE.DABH
     *
     * @mbggenerated
     */
    public void setDabh(String dabh) {
        this.dabh = dabh == null ? null : dabh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.FZJG
     *
     * @return the value of BIZ_VIO_FORCE.FZJG
     *
     * @mbggenerated
     */
    public String getFzjg() {
        return fzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.FZJG
     *
     * @param fzjg the value for BIZ_VIO_FORCE.FZJG
     *
     * @mbggenerated
     */
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg == null ? null : fzjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.ZJCX
     *
     * @return the value of BIZ_VIO_FORCE.ZJCX
     *
     * @mbggenerated
     */
    public String getZjcx() {
        return zjcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.ZJCX
     *
     * @param zjcx the value for BIZ_VIO_FORCE.ZJCX
     *
     * @mbggenerated
     */
    public void setZjcx(String zjcx) {
        this.zjcx = zjcx == null ? null : zjcx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.DSR
     *
     * @return the value of BIZ_VIO_FORCE.DSR
     *
     * @mbggenerated
     */
    public String getDsr() {
        return dsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.DSR
     *
     * @param dsr the value for BIZ_VIO_FORCE.DSR
     *
     * @mbggenerated
     */
    public void setDsr(String dsr) {
        this.dsr = dsr == null ? null : dsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.ZSXZQH
     *
     * @return the value of BIZ_VIO_FORCE.ZSXZQH
     *
     * @mbggenerated
     */
    public String getZsxzqh() {
        return zsxzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.ZSXZQH
     *
     * @param zsxzqh the value for BIZ_VIO_FORCE.ZSXZQH
     *
     * @mbggenerated
     */
    public void setZsxzqh(String zsxzqh) {
        this.zsxzqh = zsxzqh == null ? null : zsxzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.ZSXXDZ
     *
     * @return the value of BIZ_VIO_FORCE.ZSXXDZ
     *
     * @mbggenerated
     */
    public String getZsxxdz() {
        return zsxxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.ZSXXDZ
     *
     * @param zsxxdz the value for BIZ_VIO_FORCE.ZSXXDZ
     *
     * @mbggenerated
     */
    public void setZsxxdz(String zsxxdz) {
        this.zsxxdz = zsxxdz == null ? null : zsxxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.DH
     *
     * @return the value of BIZ_VIO_FORCE.DH
     *
     * @mbggenerated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.DH
     *
     * @param dh the value for BIZ_VIO_FORCE.DH
     *
     * @mbggenerated
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.LXFS
     *
     * @return the value of BIZ_VIO_FORCE.LXFS
     *
     * @mbggenerated
     */
    public String getLxfs() {
        return lxfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.LXFS
     *
     * @param lxfs the value for BIZ_VIO_FORCE.LXFS
     *
     * @mbggenerated
     */
    public void setLxfs(String lxfs) {
        this.lxfs = lxfs == null ? null : lxfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.CLFL
     *
     * @return the value of BIZ_VIO_FORCE.CLFL
     *
     * @mbggenerated
     */
    public String getClfl() {
        return clfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.CLFL
     *
     * @param clfl the value for BIZ_VIO_FORCE.CLFL
     *
     * @mbggenerated
     */
    public void setClfl(String clfl) {
        this.clfl = clfl == null ? null : clfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.HPZL
     *
     * @return the value of BIZ_VIO_FORCE.HPZL
     *
     * @mbggenerated
     */
    public String getHpzl() {
        return hpzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.HPZL
     *
     * @param hpzl the value for BIZ_VIO_FORCE.HPZL
     *
     * @mbggenerated
     */
    public void setHpzl(String hpzl) {
        this.hpzl = hpzl == null ? null : hpzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.HPHM
     *
     * @return the value of BIZ_VIO_FORCE.HPHM
     *
     * @mbggenerated
     */
    public String getHphm() {
        return hphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.HPHM
     *
     * @param hphm the value for BIZ_VIO_FORCE.HPHM
     *
     * @mbggenerated
     */
    public void setHphm(String hphm) {
        this.hphm = hphm == null ? null : hphm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.JDCSYR
     *
     * @return the value of BIZ_VIO_FORCE.JDCSYR
     *
     * @mbggenerated
     */
    public String getJdcsyr() {
        return jdcsyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.JDCSYR
     *
     * @param jdcsyr the value for BIZ_VIO_FORCE.JDCSYR
     *
     * @mbggenerated
     */
    public void setJdcsyr(String jdcsyr) {
        this.jdcsyr = jdcsyr == null ? null : jdcsyr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.FDJH
     *
     * @return the value of BIZ_VIO_FORCE.FDJH
     *
     * @mbggenerated
     */
    public String getFdjh() {
        return fdjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.FDJH
     *
     * @param fdjh the value for BIZ_VIO_FORCE.FDJH
     *
     * @mbggenerated
     */
    public void setFdjh(String fdjh) {
        this.fdjh = fdjh == null ? null : fdjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.CLSBDH
     *
     * @return the value of BIZ_VIO_FORCE.CLSBDH
     *
     * @mbggenerated
     */
    public String getClsbdh() {
        return clsbdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.CLSBDH
     *
     * @param clsbdh the value for BIZ_VIO_FORCE.CLSBDH
     *
     * @mbggenerated
     */
    public void setClsbdh(String clsbdh) {
        this.clsbdh = clsbdh == null ? null : clsbdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.SYXZ
     *
     * @return the value of BIZ_VIO_FORCE.SYXZ
     *
     * @mbggenerated
     */
    public String getSyxz() {
        return syxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.SYXZ
     *
     * @param syxz the value for BIZ_VIO_FORCE.SYXZ
     *
     * @mbggenerated
     */
    public void setSyxz(String syxz) {
        this.syxz = syxz == null ? null : syxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.JTFS
     *
     * @return the value of BIZ_VIO_FORCE.JTFS
     *
     * @mbggenerated
     */
    public String getJtfs() {
        return jtfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.JTFS
     *
     * @param jtfs the value for BIZ_VIO_FORCE.JTFS
     *
     * @mbggenerated
     */
    public void setJtfs(String jtfs) {
        this.jtfs = jtfs == null ? null : jtfs.trim();
    }


    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getWfsj() {
        return wfsj;
    }

    @JsonDeserialize(using = CustomJsonDateDeserializer.class)
    public void setWfsj(Date wfsj) {
        this.wfsj = wfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.XZQH
     *
     * @return the value of BIZ_VIO_FORCE.XZQH
     *
     * @mbggenerated
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.XZQH
     *
     * @param xzqh the value for BIZ_VIO_FORCE.XZQH
     *
     * @mbggenerated
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh == null ? null : xzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.WFDD
     *
     * @return the value of BIZ_VIO_FORCE.WFDD
     *
     * @mbggenerated
     */
    public String getWfdd() {
        return wfdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.WFDD
     *
     * @param wfdd the value for BIZ_VIO_FORCE.WFDD
     *
     * @mbggenerated
     */
    public void setWfdd(String wfdd) {
        this.wfdd = wfdd == null ? null : wfdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.LDDM
     *
     * @return the value of BIZ_VIO_FORCE.LDDM
     *
     * @mbggenerated
     */
    public String getLddm() {
        return lddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.LDDM
     *
     * @param lddm the value for BIZ_VIO_FORCE.LDDM
     *
     * @mbggenerated
     */
    public void setLddm(String lddm) {
        this.lddm = lddm == null ? null : lddm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.DDMS
     *
     * @return the value of BIZ_VIO_FORCE.DDMS
     *
     * @mbggenerated
     */
    public String getDdms() {
        return ddms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.DDMS
     *
     * @param ddms the value for BIZ_VIO_FORCE.DDMS
     *
     * @mbggenerated
     */
    public void setDdms(String ddms) {
        this.ddms = ddms == null ? null : ddms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.WFDZ
     *
     * @return the value of BIZ_VIO_FORCE.WFDZ
     *
     * @mbggenerated
     */
    public String getWfdz() {
        return wfdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.WFDZ
     *
     * @param wfdz the value for BIZ_VIO_FORCE.WFDZ
     *
     * @mbggenerated
     */
    public void setWfdz(String wfdz) {
        this.wfdz = wfdz == null ? null : wfdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.WFXW1
     *
     * @return the value of BIZ_VIO_FORCE.WFXW1
     *
     * @mbggenerated
     */
    public String getWfxw1() {
        return wfxw1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.WFXW1
     *
     * @param wfxw1 the value for BIZ_VIO_FORCE.WFXW1
     *
     * @mbggenerated
     */
    public void setWfxw1(String wfxw1) {
        this.wfxw1 = wfxw1 == null ? null : wfxw1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.SCZ1
     *
     * @return the value of BIZ_VIO_FORCE.SCZ1
     *
     * @mbggenerated
     */
    public String getScz1() {
        return scz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.SCZ1
     *
     * @param scz1 the value for BIZ_VIO_FORCE.SCZ1
     *
     * @mbggenerated
     */
    public void setScz1(String scz1) {
        this.scz1 = scz1 == null ? null : scz1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.BZZ1
     *
     * @return the value of BIZ_VIO_FORCE.BZZ1
     *
     * @mbggenerated
     */
    public String getBzz1() {
        return bzz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.BZZ1
     *
     * @param bzz1 the value for BIZ_VIO_FORCE.BZZ1
     *
     * @mbggenerated
     */
    public void setBzz1(String bzz1) {
        this.bzz1 = bzz1 == null ? null : bzz1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.WFXW2
     *
     * @return the value of BIZ_VIO_FORCE.WFXW2
     *
     * @mbggenerated
     */
    public String getWfxw2() {
        return wfxw2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.WFXW2
     *
     * @param wfxw2 the value for BIZ_VIO_FORCE.WFXW2
     *
     * @mbggenerated
     */
    public void setWfxw2(String wfxw2) {
        this.wfxw2 = wfxw2 == null ? null : wfxw2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.SCZ2
     *
     * @return the value of BIZ_VIO_FORCE.SCZ2
     *
     * @mbggenerated
     */
    public String getScz2() {
        return scz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.SCZ2
     *
     * @param scz2 the value for BIZ_VIO_FORCE.SCZ2
     *
     * @mbggenerated
     */
    public void setScz2(String scz2) {
        this.scz2 = scz2 == null ? null : scz2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.BZZ2
     *
     * @return the value of BIZ_VIO_FORCE.BZZ2
     *
     * @mbggenerated
     */
    public String getBzz2() {
        return bzz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.BZZ2
     *
     * @param bzz2 the value for BIZ_VIO_FORCE.BZZ2
     *
     * @mbggenerated
     */
    public void setBzz2(String bzz2) {
        this.bzz2 = bzz2 == null ? null : bzz2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.WFXW3
     *
     * @return the value of BIZ_VIO_FORCE.WFXW3
     *
     * @mbggenerated
     */
    public String getWfxw3() {
        return wfxw3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.WFXW3
     *
     * @param wfxw3 the value for BIZ_VIO_FORCE.WFXW3
     *
     * @mbggenerated
     */
    public void setWfxw3(String wfxw3) {
        this.wfxw3 = wfxw3 == null ? null : wfxw3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.SCZ3
     *
     * @return the value of BIZ_VIO_FORCE.SCZ3
     *
     * @mbggenerated
     */
    public String getScz3() {
        return scz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.SCZ3
     *
     * @param scz3 the value for BIZ_VIO_FORCE.SCZ3
     *
     * @mbggenerated
     */
    public void setScz3(String scz3) {
        this.scz3 = scz3 == null ? null : scz3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.BZZ3
     *
     * @return the value of BIZ_VIO_FORCE.BZZ3
     *
     * @mbggenerated
     */
    public String getBzz3() {
        return bzz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.BZZ3
     *
     * @param bzz3 the value for BIZ_VIO_FORCE.BZZ3
     *
     * @mbggenerated
     */
    public void setBzz3(String bzz3) {
        this.bzz3 = bzz3 == null ? null : bzz3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.WFXW4
     *
     * @return the value of BIZ_VIO_FORCE.WFXW4
     *
     * @mbggenerated
     */
    public String getWfxw4() {
        return wfxw4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.WFXW4
     *
     * @param wfxw4 the value for BIZ_VIO_FORCE.WFXW4
     *
     * @mbggenerated
     */
    public void setWfxw4(String wfxw4) {
        this.wfxw4 = wfxw4 == null ? null : wfxw4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.SCZ4
     *
     * @return the value of BIZ_VIO_FORCE.SCZ4
     *
     * @mbggenerated
     */
    public String getScz4() {
        return scz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.SCZ4
     *
     * @param scz4 the value for BIZ_VIO_FORCE.SCZ4
     *
     * @mbggenerated
     */
    public void setScz4(String scz4) {
        this.scz4 = scz4 == null ? null : scz4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.BZZ4
     *
     * @return the value of BIZ_VIO_FORCE.BZZ4
     *
     * @mbggenerated
     */
    public String getBzz4() {
        return bzz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.BZZ4
     *
     * @param bzz4 the value for BIZ_VIO_FORCE.BZZ4
     *
     * @mbggenerated
     */
    public void setBzz4(String bzz4) {
        this.bzz4 = bzz4 == null ? null : bzz4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.WFXW5
     *
     * @return the value of BIZ_VIO_FORCE.WFXW5
     *
     * @mbggenerated
     */
    public String getWfxw5() {
        return wfxw5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.WFXW5
     *
     * @param wfxw5 the value for BIZ_VIO_FORCE.WFXW5
     *
     * @mbggenerated
     */
    public void setWfxw5(String wfxw5) {
        this.wfxw5 = wfxw5 == null ? null : wfxw5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.SCZ5
     *
     * @return the value of BIZ_VIO_FORCE.SCZ5
     *
     * @mbggenerated
     */
    public String getScz5() {
        return scz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.SCZ5
     *
     * @param scz5 the value for BIZ_VIO_FORCE.SCZ5
     *
     * @mbggenerated
     */
    public void setScz5(String scz5) {
        this.scz5 = scz5 == null ? null : scz5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.BZZ5
     *
     * @return the value of BIZ_VIO_FORCE.BZZ5
     *
     * @mbggenerated
     */
    public String getBzz5() {
        return bzz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.BZZ5
     *
     * @param bzz5 the value for BIZ_VIO_FORCE.BZZ5
     *
     * @mbggenerated
     */
    public void setBzz5(String bzz5) {
        this.bzz5 = bzz5 == null ? null : bzz5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.ZQMJ
     *
     * @return the value of BIZ_VIO_FORCE.ZQMJ
     *
     * @mbggenerated
     */
    public String getZqmj() {
        return zqmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.ZQMJ
     *
     * @param zqmj the value for BIZ_VIO_FORCE.ZQMJ
     *
     * @mbggenerated
     */
    public void setZqmj(String zqmj) {
        this.zqmj = zqmj == null ? null : zqmj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.FXJG
     *
     * @return the value of BIZ_VIO_FORCE.FXJG
     *
     * @mbggenerated
     */
    public String getFxjg() {
        return fxjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.FXJG
     *
     * @param fxjg the value for BIZ_VIO_FORCE.FXJG
     *
     * @mbggenerated
     */
    public void setFxjg(String fxjg) {
        this.fxjg = fxjg == null ? null : fxjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.JSJQBJ
     *
     * @return the value of BIZ_VIO_FORCE.JSJQBJ
     *
     * @mbggenerated
     */
    public String getJsjqbj() {
        return jsjqbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.JSJQBJ
     *
     * @param jsjqbj the value for BIZ_VIO_FORCE.JSJQBJ
     *
     * @mbggenerated
     */
    public void setJsjqbj(String jsjqbj) {
        this.jsjqbj = jsjqbj == null ? null : jsjqbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.SGDJ
     *
     * @return the value of BIZ_VIO_FORCE.SGDJ
     *
     * @mbggenerated
     */
    public String getSgdj() {
        return sgdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.SGDJ
     *
     * @param sgdj the value for BIZ_VIO_FORCE.SGDJ
     *
     * @mbggenerated
     */
    public void setSgdj(String sgdj) {
        this.sgdj = sgdj == null ? null : sgdj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.MJYJ
     *
     * @return the value of BIZ_VIO_FORCE.MJYJ
     *
     * @mbggenerated
     */
    public String getMjyj() {
        return mjyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.MJYJ
     *
     * @param mjyj the value for BIZ_VIO_FORCE.MJYJ
     *
     * @mbggenerated
     */
    public void setMjyj(String mjyj) {
        this.mjyj = mjyj == null ? null : mjyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.JD
     *
     * @return the value of BIZ_VIO_FORCE.JD
     *
     * @mbggenerated
     */
    public String getJd() {
        return jd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.JD
     *
     * @param jd the value for BIZ_VIO_FORCE.JD
     *
     * @mbggenerated
     */
    public void setJd(String jd) {
        this.jd = jd == null ? null : jd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.WD
     *
     * @return the value of BIZ_VIO_FORCE.WD
     *
     * @mbggenerated
     */
    public String getWd() {
        return wd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.WD
     *
     * @param wd the value for BIZ_VIO_FORCE.WD
     *
     * @mbggenerated
     */
    public void setWd(String wd) {
        this.wd = wd == null ? null : wd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.GLS
     *
     * @return the value of BIZ_VIO_FORCE.GLS
     *
     * @mbggenerated
     */
    public String getGls() {
        return gls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.GLS
     *
     * @param gls the value for BIZ_VIO_FORCE.GLS
     *
     * @mbggenerated
     */
    public void setGls(String gls) {
        this.gls = gls == null ? null : gls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.FLYJ
     *
     * @return the value of BIZ_VIO_FORCE.FLYJ
     *
     * @mbggenerated
     */
    public String getFlyj() {
        return flyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.FLYJ
     *
     * @param flyj the value for BIZ_VIO_FORCE.FLYJ
     *
     * @mbggenerated
     */
    public void setFlyj(String flyj) {
        this.flyj = flyj == null ? null : flyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.DSRYY
     *
     * @return the value of BIZ_VIO_FORCE.DSRYY
     *
     * @mbggenerated
     */
    public String getDsryy() {
        return dsryy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.DSRYY
     *
     * @param dsryy the value for BIZ_VIO_FORCE.DSRYY
     *
     * @mbggenerated
     */
    public void setDsryy(String dsryy) {
        this.dsryy = dsryy == null ? null : dsryy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.BZ
     *
     * @return the value of BIZ_VIO_FORCE.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.BZ
     *
     * @param bz the value for BIZ_VIO_FORCE.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.DYBJ
     *
     * @return the value of BIZ_VIO_FORCE.DYBJ
     *
     * @mbggenerated
     */
    public Short getDybj() {
        return dybj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.DYBJ
     *
     * @param dybj the value for BIZ_VIO_FORCE.DYBJ
     *
     * @mbggenerated
     */
    public void setDybj(Short dybj) {
        this.dybj = dybj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_FORCE.DYCS
     *
     * @return the value of BIZ_VIO_FORCE.DYCS
     *
     * @mbggenerated
     */
    public Short getDycs() {
        return dycs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_FORCE.DYCS
     *
     * @param dycs the value for BIZ_VIO_FORCE.DYCS
     *
     * @mbggenerated
     */
    public void setDycs(Short dycs) {
        this.dycs = dycs;
    }
}