package com.scxd.beans.pojo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.scxd.common.CustomDateSerializer;
import com.scxd.common.CustomJsonDateDeserializer;

import java.util.Date;
@JsonIgnoreProperties(ignoreUnknown = true)
public class BizVioViolation {

    private String id  = "";

    private String wfxq  = "";

    public String getWfxq() {
        return wfxq;
    }

    public void setWfxq(String wfxq) {
        this.wfxq = wfxq;
    }

    private String jdsbh  = "";

    private String ryfl  = "";

    private String jszh  = "";

    private String hpzlname ="";

    private String lrrname = "";

    private String dabh  = "";

    private String fzjg  = "";

    private String zjcx = "";

    private String dsr = "";


    private String zsxzqh = "";


    private String zsxxdz  = "";


    private String dh  = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.LXFS
     *
     * @mbggenerated
     */
    private String lxfs = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.CLFL
     *
     * @mbggenerated
     */
    private String clfl = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.HPZL
     *
     * @mbggenerated
     */
    private String hpzl = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.HPHM
     *
     * @mbggenerated
     */
    private String hphm = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.JDCSYR
     *
     * @mbggenerated
     */
    private String jdcsyr = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.SYXZ
     *
     * @mbggenerated
     */
    private String syxz = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.JTFS
     *
     * @mbggenerated
     */
    private String jtfs = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.WFSJ
     *
     * @mbggenerated
     */
    private Date wfsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.XZQH
     *
     * @mbggenerated
     */
    private String xzqh = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.WFDD
     *
     * @mbggenerated
     */
    private String wfdd = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.LDDM
     *
     * @mbggenerated
     */
    private String lddm = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.DDMS
     *
     * @mbggenerated
     */
    private String ddms = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.WFDZ
     *
     * @mbggenerated
     */
    private String wfdz = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.WFXW
     *
     * @mbggenerated
     */
    private String wfxw = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.SCZ
     *
     * @mbggenerated
     */
    private String scz = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.BZZ
     *
     * @mbggenerated
     */
    private String bzz = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.CFZL
     *
     * @mbggenerated
     */
    private String cfzl = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.FKJE
     *
     * @mbggenerated
     */
    private Short fkje = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.ZQMJ
     *
     * @mbggenerated
     */
    private String zqmj  = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.JKFS
     *
     * @mbggenerated
     */
    private String jkfs  = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.JKBJ
     *
     * @mbggenerated
     */
    private String jkbj = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.JKRQ
     *
     * @mbggenerated
     */
    private Date jkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.FXJG
     *
     * @mbggenerated
     */
    private String fxjg = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.CLSJ
     *
     * @mbggenerated
     */
    private Date clsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.JSJQBJ
     *
     * @mbggenerated
     */
    private String jsjqbj = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.SGDJ
     *
     * @mbggenerated
     */
    private String sgdj = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.JD
     *
     * @mbggenerated
     */
    private String jd = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.WD
     *
     * @mbggenerated
     */
    private String wd = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.WFJF
     *
     * @mbggenerated
     */
    private String wfjf = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.DYBJ
     *
     * @mbggenerated
     */
    private Short dybj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.DYCS
     *
     * @mbggenerated
     */
    private Short dycs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.WFDM
     *
     * @mbggenerated
     */
    private String wfdm = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.GLS
     *
     * @mbggenerated
     */
    private String gls = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_VIOLATION.WFNR
     *
     * @mbggenerated
     */
    private String wfnr = "";



    private String lrr = "";

    private String bmbh = "";
    private  String  wsjyw = "";

    private  String  xzssjg = "";

    public String getXzssjg() {
        return xzssjg;
    }

    public void setXzssjg(String xzssjg) {
        this.xzssjg = xzssjg;
    }

    public String getWsjyw() {
        return wsjyw;
    }

    public void setWsjyw(String wsjyw) {
        this.wsjyw = wsjyw;
    }

    public String getBmbh() {
        return bmbh;
    }

    public void setBmbh(String bmbh) {
        this.bmbh = bmbh;
    }

    public String getLrr() {
        return lrr;
    }

    public void setLrr(String lrr) {
        this.lrr = lrr;
    }

    public String getHpzlname() {
        return hpzlname;
    }

    public void setHpzlname(String hpzlname) {
        this.hpzlname = hpzlname;
    }

    public String getLrrname() {
        return lrrname;
    }

    public void setLrrname(String lrrname) {
        this.lrrname = lrrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.ID
     *
     * @return the value of BIZ_VIO_VIOLATION.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.ID
     *
     * @param id the value for BIZ_VIO_VIOLATION.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.JDSBH
     *
     * @return the value of BIZ_VIO_VIOLATION.JDSBH
     *
     * @mbggenerated
     */
    public String getJdsbh() {
        return jdsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.JDSBH
     *
     * @param jdsbh the value for BIZ_VIO_VIOLATION.JDSBH
     *
     * @mbggenerated
     */
    public void setJdsbh(String jdsbh) {
        this.jdsbh = jdsbh == null ? null : jdsbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.RYFL
     *
     * @return the value of BIZ_VIO_VIOLATION.RYFL
     *
     * @mbggenerated
     */
    public String getRyfl() {
        return ryfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.RYFL
     *
     * @param ryfl the value for BIZ_VIO_VIOLATION.RYFL
     *
     * @mbggenerated
     */
    public void setRyfl(String ryfl) {
        this.ryfl = ryfl == null ? null : ryfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.JSZH
     *
     * @return the value of BIZ_VIO_VIOLATION.JSZH
     *
     * @mbggenerated
     */
    public String getJszh() {
        return jszh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.JSZH
     *
     * @param jszh the value for BIZ_VIO_VIOLATION.JSZH
     *
     * @mbggenerated
     */
    public void setJszh(String jszh) {
        this.jszh = jszh == null ? null : jszh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.DABH
     *
     * @return the value of BIZ_VIO_VIOLATION.DABH
     *
     * @mbggenerated
     */
    public String getDabh() {
        return dabh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.DABH
     *
     * @param dabh the value for BIZ_VIO_VIOLATION.DABH
     *
     * @mbggenerated
     */
    public void setDabh(String dabh) {
        this.dabh = dabh == null ? null : dabh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.FZJG
     *
     * @return the value of BIZ_VIO_VIOLATION.FZJG
     *
     * @mbggenerated
     */
    public String getFzjg() {
        return fzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.FZJG
     *
     * @param fzjg the value for BIZ_VIO_VIOLATION.FZJG
     *
     * @mbggenerated
     */
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg == null ? null : fzjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.ZJCX
     *
     * @return the value of BIZ_VIO_VIOLATION.ZJCX
     *
     * @mbggenerated
     */
    public String getZjcx() {
        return zjcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.ZJCX
     *
     * @param zjcx the value for BIZ_VIO_VIOLATION.ZJCX
     *
     * @mbggenerated
     */
    public void setZjcx(String zjcx) {
        this.zjcx = zjcx == null ? null : zjcx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.DSR
     *
     * @return the value of BIZ_VIO_VIOLATION.DSR
     *
     * @mbggenerated
     */
    public String getDsr() {
        return dsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.DSR
     *
     * @param dsr the value for BIZ_VIO_VIOLATION.DSR
     *
     * @mbggenerated
     */
    public void setDsr(String dsr) {
        this.dsr = dsr == null ? null : dsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.ZSXZQH
     *
     * @return the value of BIZ_VIO_VIOLATION.ZSXZQH
     *
     * @mbggenerated
     */
    public String getZsxzqh() {
        return zsxzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.ZSXZQH
     *
     * @param zsxzqh the value for BIZ_VIO_VIOLATION.ZSXZQH
     *
     * @mbggenerated
     */
    public void setZsxzqh(String zsxzqh) {
        this.zsxzqh = zsxzqh == null ? null : zsxzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.ZSXXDZ
     *
     * @return the value of BIZ_VIO_VIOLATION.ZSXXDZ
     *
     * @mbggenerated
     */
    public String getZsxxdz() {
        return zsxxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.ZSXXDZ
     *
     * @param zsxxdz the value for BIZ_VIO_VIOLATION.ZSXXDZ
     *
     * @mbggenerated
     */
    public void setZsxxdz(String zsxxdz) {
        this.zsxxdz = zsxxdz == null ? null : zsxxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.DH
     *
     * @return the value of BIZ_VIO_VIOLATION.DH
     *
     * @mbggenerated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.DH
     *
     * @param dh the value for BIZ_VIO_VIOLATION.DH
     *
     * @mbggenerated
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.LXFS
     *
     * @return the value of BIZ_VIO_VIOLATION.LXFS
     *
     * @mbggenerated
     */
    public String getLxfs() {
        return lxfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.LXFS
     *
     * @param lxfs the value for BIZ_VIO_VIOLATION.LXFS
     *
     * @mbggenerated
     */
    public void setLxfs(String lxfs) {
        this.lxfs = lxfs == null ? null : lxfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.CLFL
     *
     * @return the value of BIZ_VIO_VIOLATION.CLFL
     *
     * @mbggenerated
     */
    public String getClfl() {
        return clfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.CLFL
     *
     * @param clfl the value for BIZ_VIO_VIOLATION.CLFL
     *
     * @mbggenerated
     */
    public void setClfl(String clfl) {
        this.clfl = clfl == null ? null : clfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.HPZL
     *
     * @return the value of BIZ_VIO_VIOLATION.HPZL
     *
     * @mbggenerated
     */
    public String getHpzl() {
        return hpzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.HPZL
     *
     * @param hpzl the value for BIZ_VIO_VIOLATION.HPZL
     *
     * @mbggenerated
     */
    public void setHpzl(String hpzl) {
        this.hpzl = hpzl == null ? null : hpzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.HPHM
     *
     * @return the value of BIZ_VIO_VIOLATION.HPHM
     *
     * @mbggenerated
     */
    public String getHphm() {
        return hphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.HPHM
     *
     * @param hphm the value for BIZ_VIO_VIOLATION.HPHM
     *
     * @mbggenerated
     */
    public void setHphm(String hphm) {
        this.hphm = hphm == null ? null : hphm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.JDCSYR
     *
     * @return the value of BIZ_VIO_VIOLATION.JDCSYR
     *
     * @mbggenerated
     */
    public String getJdcsyr() {
        return jdcsyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.JDCSYR
     *
     * @param jdcsyr the value for BIZ_VIO_VIOLATION.JDCSYR
     *
     * @mbggenerated
     */
    public void setJdcsyr(String jdcsyr) {
        this.jdcsyr = jdcsyr == null ? null : jdcsyr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.SYXZ
     *
     * @return the value of BIZ_VIO_VIOLATION.SYXZ
     *
     * @mbggenerated
     */
    public String getSyxz() {
        return syxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.SYXZ
     *
     * @param syxz the value for BIZ_VIO_VIOLATION.SYXZ
     *
     * @mbggenerated
     */
    public void setSyxz(String syxz) {
        this.syxz = syxz == null ? null : syxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.JTFS
     *
     * @return the value of BIZ_VIO_VIOLATION.JTFS
     *
     * @mbggenerated
     */
    public String getJtfs() {
        return jtfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.JTFS
     *
     * @param jtfs the value for BIZ_VIO_VIOLATION.JTFS
     *
     * @mbggenerated
     */
    public void setJtfs(String jtfs) {
        this.jtfs = jtfs == null ? null : jtfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.WFSJ
     *
     * @return the value of BIZ_VIO_VIOLATION.WFSJ
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getWfsj() {
        return wfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.WFSJ
     *
     * @param wfsj the value for BIZ_VIO_VIOLATION.WFSJ
     *
     * @mbggenerated
     */
    @JsonDeserialize(using = CustomJsonDateDeserializer.class)
    public void setWfsj(Date wfsj) {
        this.wfsj = wfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.XZQH
     *
     * @return the value of BIZ_VIO_VIOLATION.XZQH
     *
     * @mbggenerated
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.XZQH
     *
     * @param xzqh the value for BIZ_VIO_VIOLATION.XZQH
     *
     * @mbggenerated
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh == null ? null : xzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.WFDD
     *
     * @return the value of BIZ_VIO_VIOLATION.WFDD
     *
     * @mbggenerated
     */
    public String getWfdd() {
        return wfdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.WFDD
     *
     * @param wfdd the value for BIZ_VIO_VIOLATION.WFDD
     *
     * @mbggenerated
     */
    public void setWfdd(String wfdd) {
        this.wfdd = wfdd == null ? null : wfdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.LDDM
     *
     * @return the value of BIZ_VIO_VIOLATION.LDDM
     *
     * @mbggenerated
     */
    public String getLddm() {
        return lddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.LDDM
     *
     * @param lddm the value for BIZ_VIO_VIOLATION.LDDM
     *
     * @mbggenerated
     */
    public void setLddm(String lddm) {
        this.lddm = lddm == null ? null : lddm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.DDMS
     *
     * @return the value of BIZ_VIO_VIOLATION.DDMS
     *
     * @mbggenerated
     */
    public String getDdms() {
        return ddms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.DDMS
     *
     * @param ddms the value for BIZ_VIO_VIOLATION.DDMS
     *
     * @mbggenerated
     */
    public void setDdms(String ddms) {
        this.ddms = ddms == null ? null : ddms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.WFDZ
     *
     * @return the value of BIZ_VIO_VIOLATION.WFDZ
     *
     * @mbggenerated
     */
    public String getWfdz() {
        return wfdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.WFDZ
     *
     * @param wfdz the value for BIZ_VIO_VIOLATION.WFDZ
     *
     * @mbggenerated
     */
    public void setWfdz(String wfdz) {
        this.wfdz = wfdz == null ? null : wfdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.WFXW
     *
     * @return the value of BIZ_VIO_VIOLATION.WFXW
     *
     * @mbggenerated
     */
    public String getWfxw() {
        return wfxw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.WFXW
     *
     * @param wfxw the value for BIZ_VIO_VIOLATION.WFXW
     *
     * @mbggenerated
     */
    public void setWfxw(String wfxw) {
        this.wfxw = wfxw == null ? null : wfxw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.SCZ
     *
     * @return the value of BIZ_VIO_VIOLATION.SCZ
     *
     * @mbggenerated
     */
    public String getScz() {
        return scz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.SCZ
     *
     * @param scz the value for BIZ_VIO_VIOLATION.SCZ
     *
     * @mbggenerated
     */
    public void setScz(String scz) {
        this.scz = scz == null ? null : scz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.BZZ
     *
     * @return the value of BIZ_VIO_VIOLATION.BZZ
     *
     * @mbggenerated
     */
    public String getBzz() {
        return bzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.BZZ
     *
     * @param bzz the value for BIZ_VIO_VIOLATION.BZZ
     *
     * @mbggenerated
     */
    public void setBzz(String bzz) {
        this.bzz = bzz == null ? null : bzz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.CFZL
     *
     * @return the value of BIZ_VIO_VIOLATION.CFZL
     *
     * @mbggenerated
     */
    public String getCfzl() {
        return cfzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.CFZL
     *
     * @param cfzl the value for BIZ_VIO_VIOLATION.CFZL
     *
     * @mbggenerated
     */
    public void setCfzl(String cfzl) {
        this.cfzl = cfzl == null ? null : cfzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.FKJE
     *
     * @return the value of BIZ_VIO_VIOLATION.FKJE
     *
     * @mbggenerated
     */
    public Short getFkje() {
        return fkje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.FKJE
     *
     * @param fkje the value for BIZ_VIO_VIOLATION.FKJE
     *
     * @mbggenerated
     */
    public void setFkje(Short fkje) {
        this.fkje = fkje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.ZQMJ
     *
     * @return the value of BIZ_VIO_VIOLATION.ZQMJ
     *
     * @mbggenerated
     */
    public String getZqmj() {
        return zqmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.ZQMJ
     *
     * @param zqmj the value for BIZ_VIO_VIOLATION.ZQMJ
     *
     * @mbggenerated
     */
    public void setZqmj(String zqmj) {
        this.zqmj = zqmj == null ? null : zqmj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.JKFS
     *
     * @return the value of BIZ_VIO_VIOLATION.JKFS
     *
     * @mbggenerated
     */
    public String getJkfs() {
        return jkfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.JKFS
     *
     * @param jkfs the value for BIZ_VIO_VIOLATION.JKFS
     *
     * @mbggenerated
     */
    public void setJkfs(String jkfs) {
        this.jkfs = jkfs == null ? null : jkfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.JKBJ
     *
     * @return the value of BIZ_VIO_VIOLATION.JKBJ
     *
     * @mbggenerated
     */
    public String getJkbj() {
        return jkbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.JKBJ
     *
     * @param jkbj the value for BIZ_VIO_VIOLATION.JKBJ
     *
     * @mbggenerated
     */
    public void setJkbj(String jkbj) {
        this.jkbj = jkbj == null ? null : jkbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.JKRQ
     *
     * @return the value of BIZ_VIO_VIOLATION.JKRQ
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getJkrq() {
        return jkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.JKRQ
     *
     * @param jkrq the value for BIZ_VIO_VIOLATION.JKRQ
     *
     * @mbggenerated
     */
    @JsonDeserialize(using = CustomJsonDateDeserializer.class)
    public void setJkrq(Date jkrq) {
        this.jkrq = jkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.FXJG
     *
     * @return the value of BIZ_VIO_VIOLATION.FXJG
     *
     * @mbggenerated
     */
    public String getFxjg() {
        return fxjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.FXJG
     *
     * @param fxjg the value for BIZ_VIO_VIOLATION.FXJG
     *
     * @mbggenerated
     */
    public void setFxjg(String fxjg) {
        this.fxjg = fxjg == null ? null : fxjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.CLSJ
     *
     * @return the value of BIZ_VIO_VIOLATION.CLSJ
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getClsj() {
        return clsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.CLSJ
     *
     * @param clsj the value for BIZ_VIO_VIOLATION.CLSJ
     *
     * @mbggenerated
     */
    @JsonDeserialize(using = CustomJsonDateDeserializer.class)
    public void setClsj(Date clsj) {
        this.clsj = clsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.JSJQBJ
     *
     * @return the value of BIZ_VIO_VIOLATION.JSJQBJ
     *
     * @mbggenerated
     */
    public String getJsjqbj() {
        return jsjqbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.JSJQBJ
     *
     * @param jsjqbj the value for BIZ_VIO_VIOLATION.JSJQBJ
     *
     * @mbggenerated
     */
    public void setJsjqbj(String jsjqbj) {
        this.jsjqbj = jsjqbj == null ? null : jsjqbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.SGDJ
     *
     * @return the value of BIZ_VIO_VIOLATION.SGDJ
     *
     * @mbggenerated
     */
    public String getSgdj() {
        return sgdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.SGDJ
     *
     * @param sgdj the value for BIZ_VIO_VIOLATION.SGDJ
     *
     * @mbggenerated
     */
    public void setSgdj(String sgdj) {
        this.sgdj = sgdj == null ? null : sgdj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.JD
     *
     * @return the value of BIZ_VIO_VIOLATION.JD
     *
     * @mbggenerated
     */
    public String getJd() {
        return jd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.JD
     *
     * @param jd the value for BIZ_VIO_VIOLATION.JD
     *
     * @mbggenerated
     */
    public void setJd(String jd) {
        this.jd = jd == null ? null : jd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.WD
     *
     * @return the value of BIZ_VIO_VIOLATION.WD
     *
     * @mbggenerated
     */
    public String getWd() {
        return wd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.WD
     *
     * @param wd the value for BIZ_VIO_VIOLATION.WD
     *
     * @mbggenerated
     */
    public void setWd(String wd) {
        this.wd = wd == null ? null : wd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.WFJF
     *
     * @return the value of BIZ_VIO_VIOLATION.WFJF
     *
     * @mbggenerated
     */
    public String getWfjf() {
        return wfjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.WFJF
     *
     * @param wfjf the value for BIZ_VIO_VIOLATION.WFJF
     *
     * @mbggenerated
     */
    public void setWfjf(String wfjf) {
        this.wfjf = wfjf == null ? null : wfjf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.DYBJ
     *
     * @return the value of BIZ_VIO_VIOLATION.DYBJ
     *
     * @mbggenerated
     */
    public Short getDybj() {
        return dybj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.DYBJ
     *
     * @param dybj the value for BIZ_VIO_VIOLATION.DYBJ
     *
     * @mbggenerated
     */
    public void setDybj(Short dybj) {
        this.dybj = dybj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.DYCS
     *
     * @return the value of BIZ_VIO_VIOLATION.DYCS
     *
     * @mbggenerated
     */
    public Short getDycs() {
        return dycs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.DYCS
     *
     * @param dycs the value for BIZ_VIO_VIOLATION.DYCS
     *
     * @mbggenerated
     */
    public void setDycs(Short dycs) {
        this.dycs = dycs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.WFDM
     *
     * @return the value of BIZ_VIO_VIOLATION.WFDM
     *
     * @mbggenerated
     */
    public String getWfdm() {
        return wfdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.WFDM
     *
     * @param wfdm the value for BIZ_VIO_VIOLATION.WFDM
     *
     * @mbggenerated
     */
    public void setWfdm(String wfdm) {
        this.wfdm = wfdm == null ? null : wfdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.GLS
     *
     * @return the value of BIZ_VIO_VIOLATION.GLS
     *
     * @mbggenerated
     */
    public String getGls() {
        return gls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.GLS
     *
     * @param gls the value for BIZ_VIO_VIOLATION.GLS
     *
     * @mbggenerated
     */
    public void setGls(String gls) {
        this.gls = gls == null ? null : gls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_VIOLATION.WFNR
     *
     * @return the value of BIZ_VIO_VIOLATION.WFNR
     *
     * @mbggenerated
     */
    public String getWfnr() {
        return wfnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_VIOLATION.WFNR
     *
     * @param wfnr the value for BIZ_VIO_VIOLATION.WFNR
     *
     * @mbggenerated
     */
    public void setWfnr(String wfnr) {
        this.wfnr = wfnr == null ? null : wfnr.trim();
    }
}