package com.scxd.beans.pojo;

import java.util.Date;

public class SysDepartment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.ID
     *
     * @mbggenerated
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.PARENTID
     *
     * @mbggenerated
     */
    private Short parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.BMBH
     *
     * @mbggenerated
     */
    private String bmbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.SJZDBMBH
     *
     * @mbggenerated
     */
    private String sjzdbmbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.LEVELNUM
     *
     * @mbggenerated
     */
    private Short levelnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.TYPE
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.NAME
     *
     * @mbggenerated
     */
    private Object name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.FAX
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.LXR
     *
     * @mbggenerated
     */
    private Object lxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.LXRDH
     *
     * @mbggenerated
     */
    private String lxrdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.LXDZ
     *
     * @mbggenerated
     */
    private Object lxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.ZT
     *
     * @mbggenerated
     */
    private Short zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.BZ
     *
     * @mbggenerated
     */
    private Object bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.CZRYZH
     *
     * @mbggenerated
     */
    private String czryzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.CZSJ
     *
     * @mbggenerated
     */
    private Date czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.FZJG
     *
     * @mbggenerated
     */
    private String fzjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.SFZSBM
     *
     * @mbggenerated
     */
    private Short sfzsbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.FZR
     *
     * @mbggenerated
     */
    private Object fzr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.ZSBMBHS
     *
     * @mbggenerated
     */
    private String zsbmbhs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.CYQXH
     *
     * @mbggenerated
     */
    private String cyqxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.XZQH
     *
     * @mbggenerated
     */
    private String xzqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPARTMENT.YWZDBMBH
     *
     * @mbggenerated
     */
    private String ywzdbmbh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.ID
     *
     * @return the value of SYS_DEPARTMENT.ID
     *
     * @mbggenerated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.ID
     *
     * @param id the value for SYS_DEPARTMENT.ID
     *
     * @mbggenerated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.PARENTID
     *
     * @return the value of SYS_DEPARTMENT.PARENTID
     *
     * @mbggenerated
     */
    public Short getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.PARENTID
     *
     * @param parentid the value for SYS_DEPARTMENT.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(Short parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.BMBH
     *
     * @return the value of SYS_DEPARTMENT.BMBH
     *
     * @mbggenerated
     */
    public String getBmbh() {
        return bmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.BMBH
     *
     * @param bmbh the value for SYS_DEPARTMENT.BMBH
     *
     * @mbggenerated
     */
    public void setBmbh(String bmbh) {
        this.bmbh = bmbh == null ? null : bmbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.SJZDBMBH
     *
     * @return the value of SYS_DEPARTMENT.SJZDBMBH
     *
     * @mbggenerated
     */
    public String getSjzdbmbh() {
        return sjzdbmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.SJZDBMBH
     *
     * @param sjzdbmbh the value for SYS_DEPARTMENT.SJZDBMBH
     *
     * @mbggenerated
     */
    public void setSjzdbmbh(String sjzdbmbh) {
        this.sjzdbmbh = sjzdbmbh == null ? null : sjzdbmbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.LEVELNUM
     *
     * @return the value of SYS_DEPARTMENT.LEVELNUM
     *
     * @mbggenerated
     */
    public Short getLevelnum() {
        return levelnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.LEVELNUM
     *
     * @param levelnum the value for SYS_DEPARTMENT.LEVELNUM
     *
     * @mbggenerated
     */
    public void setLevelnum(Short levelnum) {
        this.levelnum = levelnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.TYPE
     *
     * @return the value of SYS_DEPARTMENT.TYPE
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.TYPE
     *
     * @param type the value for SYS_DEPARTMENT.TYPE
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.NAME
     *
     * @return the value of SYS_DEPARTMENT.NAME
     *
     * @mbggenerated
     */
    public Object getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.NAME
     *
     * @param name the value for SYS_DEPARTMENT.NAME
     *
     * @mbggenerated
     */
    public void setName(Object name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.FAX
     *
     * @return the value of SYS_DEPARTMENT.FAX
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.FAX
     *
     * @param fax the value for SYS_DEPARTMENT.FAX
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.LXR
     *
     * @return the value of SYS_DEPARTMENT.LXR
     *
     * @mbggenerated
     */
    public Object getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.LXR
     *
     * @param lxr the value for SYS_DEPARTMENT.LXR
     *
     * @mbggenerated
     */
    public void setLxr(Object lxr) {
        this.lxr = lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.LXRDH
     *
     * @return the value of SYS_DEPARTMENT.LXRDH
     *
     * @mbggenerated
     */
    public String getLxrdh() {
        return lxrdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.LXRDH
     *
     * @param lxrdh the value for SYS_DEPARTMENT.LXRDH
     *
     * @mbggenerated
     */
    public void setLxrdh(String lxrdh) {
        this.lxrdh = lxrdh == null ? null : lxrdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.LXDZ
     *
     * @return the value of SYS_DEPARTMENT.LXDZ
     *
     * @mbggenerated
     */
    public Object getLxdz() {
        return lxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.LXDZ
     *
     * @param lxdz the value for SYS_DEPARTMENT.LXDZ
     *
     * @mbggenerated
     */
    public void setLxdz(Object lxdz) {
        this.lxdz = lxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.ZT
     *
     * @return the value of SYS_DEPARTMENT.ZT
     *
     * @mbggenerated
     */
    public Short getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.ZT
     *
     * @param zt the value for SYS_DEPARTMENT.ZT
     *
     * @mbggenerated
     */
    public void setZt(Short zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.BZ
     *
     * @return the value of SYS_DEPARTMENT.BZ
     *
     * @mbggenerated
     */
    public Object getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.BZ
     *
     * @param bz the value for SYS_DEPARTMENT.BZ
     *
     * @mbggenerated
     */
    public void setBz(Object bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.CZRYZH
     *
     * @return the value of SYS_DEPARTMENT.CZRYZH
     *
     * @mbggenerated
     */
    public String getCzryzh() {
        return czryzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.CZRYZH
     *
     * @param czryzh the value for SYS_DEPARTMENT.CZRYZH
     *
     * @mbggenerated
     */
    public void setCzryzh(String czryzh) {
        this.czryzh = czryzh == null ? null : czryzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.CZSJ
     *
     * @return the value of SYS_DEPARTMENT.CZSJ
     *
     * @mbggenerated
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.CZSJ
     *
     * @param czsj the value for SYS_DEPARTMENT.CZSJ
     *
     * @mbggenerated
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.FZJG
     *
     * @return the value of SYS_DEPARTMENT.FZJG
     *
     * @mbggenerated
     */
    public String getFzjg() {
        return fzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.FZJG
     *
     * @param fzjg the value for SYS_DEPARTMENT.FZJG
     *
     * @mbggenerated
     */
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg == null ? null : fzjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.SFZSBM
     *
     * @return the value of SYS_DEPARTMENT.SFZSBM
     *
     * @mbggenerated
     */
    public Short getSfzsbm() {
        return sfzsbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.SFZSBM
     *
     * @param sfzsbm the value for SYS_DEPARTMENT.SFZSBM
     *
     * @mbggenerated
     */
    public void setSfzsbm(Short sfzsbm) {
        this.sfzsbm = sfzsbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.FZR
     *
     * @return the value of SYS_DEPARTMENT.FZR
     *
     * @mbggenerated
     */
    public Object getFzr() {
        return fzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.FZR
     *
     * @param fzr the value for SYS_DEPARTMENT.FZR
     *
     * @mbggenerated
     */
    public void setFzr(Object fzr) {
        this.fzr = fzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.ZSBMBHS
     *
     * @return the value of SYS_DEPARTMENT.ZSBMBHS
     *
     * @mbggenerated
     */
    public String getZsbmbhs() {
        return zsbmbhs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.ZSBMBHS
     *
     * @param zsbmbhs the value for SYS_DEPARTMENT.ZSBMBHS
     *
     * @mbggenerated
     */
    public void setZsbmbhs(String zsbmbhs) {
        this.zsbmbhs = zsbmbhs == null ? null : zsbmbhs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.CYQXH
     *
     * @return the value of SYS_DEPARTMENT.CYQXH
     *
     * @mbggenerated
     */
    public String getCyqxh() {
        return cyqxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.CYQXH
     *
     * @param cyqxh the value for SYS_DEPARTMENT.CYQXH
     *
     * @mbggenerated
     */
    public void setCyqxh(String cyqxh) {
        this.cyqxh = cyqxh == null ? null : cyqxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.XZQH
     *
     * @return the value of SYS_DEPARTMENT.XZQH
     *
     * @mbggenerated
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.XZQH
     *
     * @param xzqh the value for SYS_DEPARTMENT.XZQH
     *
     * @mbggenerated
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh == null ? null : xzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPARTMENT.YWZDBMBH
     *
     * @return the value of SYS_DEPARTMENT.YWZDBMBH
     *
     * @mbggenerated
     */
    public String getYwzdbmbh() {
        return ywzdbmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPARTMENT.YWZDBMBH
     *
     * @param ywzdbmbh the value for SYS_DEPARTMENT.YWZDBMBH
     *
     * @mbggenerated
     */
    public void setYwzdbmbh(String ywzdbmbh) {
        this.ywzdbmbh = ywzdbmbh == null ? null : ywzdbmbh.trim();
    }
}