package com.scxd.beans.pojo;

import java.util.Date;

public class SysIfLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_IF_LOG.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_IF_LOG.CJSJ
     *
     * @mbggenerated
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_IF_LOG.JKID
     *
     * @mbggenerated
     */
    private String jkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_IF_LOG.GLBM
     *
     * @mbggenerated
     */
    private String glbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_IF_LOG.WYM
     *
     * @mbggenerated
     */
    private String wym;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_IF_LOG.ID
     *
     * @return the value of SYS_IF_LOG.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_IF_LOG.ID
     *
     * @param id the value for SYS_IF_LOG.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_IF_LOG.CJSJ
     *
     * @return the value of SYS_IF_LOG.CJSJ
     *
     * @mbggenerated
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_IF_LOG.CJSJ
     *
     * @param cjsj the value for SYS_IF_LOG.CJSJ
     *
     * @mbggenerated
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_IF_LOG.JKID
     *
     * @return the value of SYS_IF_LOG.JKID
     *
     * @mbggenerated
     */
    public String getJkid() {
        return jkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_IF_LOG.JKID
     *
     * @param jkid the value for SYS_IF_LOG.JKID
     *
     * @mbggenerated
     */
    public void setJkid(String jkid) {
        this.jkid = jkid == null ? null : jkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_IF_LOG.GLBM
     *
     * @return the value of SYS_IF_LOG.GLBM
     *
     * @mbggenerated
     */
    public String getGlbm() {
        return glbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_IF_LOG.GLBM
     *
     * @param glbm the value for SYS_IF_LOG.GLBM
     *
     * @mbggenerated
     */
    public void setGlbm(String glbm) {
        this.glbm = glbm == null ? null : glbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_IF_LOG.WYM
     *
     * @return the value of SYS_IF_LOG.WYM
     *
     * @mbggenerated
     */
    public String getWym() {
        return wym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_IF_LOG.WYM
     *
     * @param wym the value for SYS_IF_LOG.WYM
     *
     * @mbggenerated
     */
    public void setWym(String wym) {
        this.wym = wym == null ? null : wym.trim();
    }
}