package com.scxd.beans.pojo;

import java.util.List;

public class SysMenu {

    private Integer menuId;

    private Integer parentid;

    private String navigateurl;

    private String name;

    private Integer mid;

    private Integer sortcode;

    private Integer state;

    private String target;

    private String ico;

    private Integer levelnum;

    private Integer sfhxyw;
    private Integer menuType;
    private Integer sfsqcb;
    private Integer sfxzjy;
    private Integer qxid;
    private Integer type;

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getQxid() {
        return qxid;
    }

    public void setQxid(Integer qxid) {
        this.qxid = qxid;
    }

    public Integer getSfxzjy() {
        return sfxzjy;
    }

    public void setSfxzjy(Integer sfxzjy) {
        this.sfxzjy = sfxzjy;
    }

    public Integer getSfhxyw() {
        return sfhxyw;
    }

    public void setSfhxyw(Integer sfhxyw) {
        this.sfhxyw = sfhxyw;
    }

    public Integer getMenuType() {
        return menuType;
    }

    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }

    public Integer getSfsqcb() {
        return sfsqcb;
    }

    public void setSfsqcb(Integer sfsqcb) {
        this.sfsqcb = sfsqcb;
    }

    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_ID
     *
     * @param menuId the value for sys_menu.MENU_ID
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.PARENTID
     *
     * @return the value of sys_menu.PARENTID
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.PARENTID
     *
     * @param parentid the value for sys_menu.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.NAVIGATEURL
     *
     * @return the value of sys_menu.NAVIGATEURL
     *
     * @mbggenerated
     */
    public String getNavigateurl() {
        return navigateurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.NAVIGATEURL
     *
     * @param navigateurl the value for sys_menu.NAVIGATEURL
     *
     * @mbggenerated
     */
    public void setNavigateurl(String navigateurl) {
        this.navigateurl = navigateurl == null ? null : navigateurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.NAME
     *
     * @return the value of sys_menu.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.NAME
     *
     * @param name the value for sys_menu.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MID
     *
     * @return the value of sys_menu.MID
     *
     * @mbggenerated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MID
     *
     * @param mid the value for sys_menu.MID
     *
     * @mbggenerated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.SORTCODE
     *
     * @return the value of sys_menu.SORTCODE
     *
     * @mbggenerated
     */
    public Integer getSortcode() {
        return sortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.SORTCODE
     *
     * @param sortcode the value for sys_menu.SORTCODE
     *
     * @mbggenerated
     */
    public void setSortcode(Integer sortcode) {
        this.sortcode = sortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.STATE
     *
     * @return the value of sys_menu.STATE
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.STATE
     *
     * @param state the value for sys_menu.STATE
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.TARGET
     *
     * @return the value of sys_menu.TARGET
     *
     * @mbggenerated
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.TARGET
     *
     * @param target the value for sys_menu.TARGET
     *
     * @mbggenerated
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.ICO
     *
     * @return the value of sys_menu.ICO
     *
     * @mbggenerated
     */
    public String getIco() {
        return ico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.ICO
     *
     * @param ico the value for sys_menu.ICO
     *
     * @mbggenerated
     */
    public void setIco(String ico) {
        this.ico = ico == null ? null : ico.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.LEVELNUM
     *
     * @return the value of sys_menu.LEVELNUM
     *
     * @mbggenerated
     */
    public Integer getLevelnum() {
        return levelnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.LEVELNUM
     *
     * @param levelnum the value for sys_menu.LEVELNUM
     *
     * @mbggenerated
     */
    public void setLevelnum(Integer levelnum) {
        this.levelnum = levelnum;
    }

    @Override
    public String toString() {
        return "SysMenu{" +
                "menuId=" + menuId +
                ", parentid=" + parentid +
                ", navigateurl='" + navigateurl + '\'' +
                ", name='" + name + '\'' +
                ", mid=" + mid +
                ", sortcode=" + sortcode +
                ", state=" + state +
                ", target='" + target + '\'' +
                ", ico='" + ico + '\'' +
                ", levelnum=" + levelnum +
                '}';
    }
}