package com.scxd.beans.pojo;

import java.util.Date;

public class SysPdaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PDA_INFO.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PDA_INFO.MC
     *
     * @mbggenerated
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PDA_INFO.BMBH
     *
     * @mbggenerated
     */
    private String bmbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PDA_INFO.WYM
     *
     * @mbggenerated
     */
    private String wym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PDA_INFO.ZT
     *
     * @mbggenerated
     */
    private Short zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PDA_INFO.CJR
     *
     * @mbggenerated
     */
    private String cjr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PDA_INFO.CJSJ
     *
     * @mbggenerated
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PDA_INFO.GXR
     *
     * @mbggenerated
     */
    private String gxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PDA_INFO.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PDA_INFO.ID
     *
     * @return the value of SYS_PDA_INFO.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PDA_INFO.ID
     *
     * @param id the value for SYS_PDA_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PDA_INFO.MC
     *
     * @return the value of SYS_PDA_INFO.MC
     *
     * @mbggenerated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PDA_INFO.MC
     *
     * @param mc the value for SYS_PDA_INFO.MC
     *
     * @mbggenerated
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PDA_INFO.BMBH
     *
     * @return the value of SYS_PDA_INFO.BMBH
     *
     * @mbggenerated
     */
    public String getBmbh() {
        return bmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PDA_INFO.BMBH
     *
     * @param bmbh the value for SYS_PDA_INFO.BMBH
     *
     * @mbggenerated
     */
    public void setBmbh(String bmbh) {
        this.bmbh = bmbh == null ? null : bmbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PDA_INFO.WYM
     *
     * @return the value of SYS_PDA_INFO.WYM
     *
     * @mbggenerated
     */
    public String getWym() {
        return wym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PDA_INFO.WYM
     *
     * @param wym the value for SYS_PDA_INFO.WYM
     *
     * @mbggenerated
     */
    public void setWym(String wym) {
        this.wym = wym == null ? null : wym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PDA_INFO.ZT
     *
     * @return the value of SYS_PDA_INFO.ZT
     *
     * @mbggenerated
     */
    public Short getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PDA_INFO.ZT
     *
     * @param zt the value for SYS_PDA_INFO.ZT
     *
     * @mbggenerated
     */
    public void setZt(Short zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PDA_INFO.CJR
     *
     * @return the value of SYS_PDA_INFO.CJR
     *
     * @mbggenerated
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PDA_INFO.CJR
     *
     * @param cjr the value for SYS_PDA_INFO.CJR
     *
     * @mbggenerated
     */
    public void setCjr(String cjr) {
        this.cjr = cjr == null ? null : cjr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PDA_INFO.CJSJ
     *
     * @return the value of SYS_PDA_INFO.CJSJ
     *
     * @mbggenerated
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PDA_INFO.CJSJ
     *
     * @param cjsj the value for SYS_PDA_INFO.CJSJ
     *
     * @mbggenerated
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PDA_INFO.GXR
     *
     * @return the value of SYS_PDA_INFO.GXR
     *
     * @mbggenerated
     */
    public String getGxr() {
        return gxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PDA_INFO.GXR
     *
     * @param gxr the value for SYS_PDA_INFO.GXR
     *
     * @mbggenerated
     */
    public void setGxr(String gxr) {
        this.gxr = gxr == null ? null : gxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PDA_INFO.GXSJ
     *
     * @return the value of SYS_PDA_INFO.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PDA_INFO.GXSJ
     *
     * @param gxsj the value for SYS_PDA_INFO.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }
}