package com.scxd.beans.pojo;

import java.util.Date;

public class SysParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.KEY
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.VALUE
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.CSLX
     *
     * @mbggenerated
     */
    private String cslx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM.CREATETIME
     *
     * @return the value of SYS_PARAM.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM.CREATETIME
     *
     * @param createtime the value for SYS_PARAM.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM.KEY
     *
     * @return the value of SYS_PARAM.KEY
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM.KEY
     *
     * @param key the value for SYS_PARAM.KEY
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM.VALUE
     *
     * @return the value of SYS_PARAM.VALUE
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM.VALUE
     *
     * @param value the value for SYS_PARAM.VALUE
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM.CSLX
     *
     * @return the value of SYS_PARAM.CSLX
     *
     * @mbggenerated
     */
    public String getCslx() {
        return cslx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM.CSLX
     *
     * @param cslx the value for SYS_PARAM.CSLX
     *
     * @mbggenerated
     */
    public void setCslx(String cslx) {
        this.cslx = cslx == null ? null : cslx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM.BZ
     *
     * @return the value of SYS_PARAM.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM.BZ
     *
     * @param bz the value for SYS_PARAM.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }
}