package com.scxd.beans.biz;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.Date;


public class BizCodeWfdm {

    private String wfxw;


    private String dmzl;


    private String dmfl;


    private String wfms;


    private String wfnr;


    private String wfgd;


    private String fltw;

    private Short wfjfs;


    private Integer fkjeMin;


    private Integer fkjeMax;

    private Integer fkjeDut;

    private String zkysMin;

    private String zkysMax;

    private String zkysDut;

    private String jlsjMin;

    private String jlsjMax;

    private String jlsjDut;

    private String qzcslx;

    private String jgbj;

    private String fkbj;

    private String zkbj;

    private String dxbj;

    private String jlbj;

    private String cxvbj;

    private String cxdbj;

    private String gb;

    private Date yxqs;

    private Date yxqz;

    private String glbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_CODEWFDM.CSBJ
     *
     * @mbggenerated
     */
    private String csbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_CODEWFDM.XH
     *
     * @mbggenerated
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_CODEWFDM.BJCSBJ
     *
     * @mbggenerated
     */
    private String bjcsbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_CODEWFDM.XRSJ
     *
     * @mbggenerated
     */
    private Date xrsj = new Date();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.WFXW
     *
     * @return the value of BIZ_CODEWFDM.WFXW
     *
     * @mbggenerated
     */
    public String getWfxw() {
        return wfxw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.WFXW
     *
     * @param wfxw the value for BIZ_CODEWFDM.WFXW
     *
     * @mbggenerated
     */
    public void setWfxw(String wfxw) {
        this.wfxw = wfxw == null ? null : wfxw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.DMZL
     *
     * @return the value of BIZ_CODEWFDM.DMZL
     *
     * @mbggenerated
     */
    public String getDmzl() {
        return dmzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.DMZL
     *
     * @param dmzl the value for BIZ_CODEWFDM.DMZL
     *
     * @mbggenerated
     */
    public void setDmzl(String dmzl) {
        this.dmzl = dmzl == null ? null : dmzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.DMFL
     *
     * @return the value of BIZ_CODEWFDM.DMFL
     *
     * @mbggenerated
     */
    public String getDmfl() {
        return dmfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.DMFL
     *
     * @param dmfl the value for BIZ_CODEWFDM.DMFL
     *
     * @mbggenerated
     */
    public void setDmfl(String dmfl) {
        this.dmfl = dmfl == null ? null : dmfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.WFMS
     *
     * @return the value of BIZ_CODEWFDM.WFMS
     *
     * @mbggenerated
     */
    public String getWfms() {
        return wfms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.WFMS
     *
     * @param wfms the value for BIZ_CODEWFDM.WFMS
     *
     * @mbggenerated
     */
    public void setWfms(String wfms) {
        this.wfms = wfms == null ? null : wfms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.WFNR
     *
     * @return the value of BIZ_CODEWFDM.WFNR
     *
     * @mbggenerated
     */
    public String getWfnr() {
        return wfnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.WFNR
     *
     * @param wfnr the value for BIZ_CODEWFDM.WFNR
     *
     * @mbggenerated
     */
    public void setWfnr(String wfnr) {
        this.wfnr = wfnr == null ? null : wfnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.WFGD
     *
     * @return the value of BIZ_CODEWFDM.WFGD
     *
     * @mbggenerated
     */
    public String getWfgd() {
        return wfgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.WFGD
     *
     * @param wfgd the value for BIZ_CODEWFDM.WFGD
     *
     * @mbggenerated
     */
    public void setWfgd(String wfgd) {
        this.wfgd = wfgd == null ? null : wfgd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.FLTW
     *
     * @return the value of BIZ_CODEWFDM.FLTW
     *
     * @mbggenerated
     */
    public String getFltw() {
        return fltw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.FLTW
     *
     * @param fltw the value for BIZ_CODEWFDM.FLTW
     *
     * @mbggenerated
     */
    public void setFltw(String fltw) {
        this.fltw = fltw == null ? null : fltw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.WFJFS
     *
     * @return the value of BIZ_CODEWFDM.WFJFS
     *
     * @mbggenerated
     */
    public Short getWfjfs() {
        return wfjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.WFJFS
     *
     * @param wfjfs the value for BIZ_CODEWFDM.WFJFS
     *
     * @mbggenerated
     */
    public void setWfjfs(Short wfjfs) {
        this.wfjfs = wfjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.FKJE_MIN
     *
     * @return the value of BIZ_CODEWFDM.FKJE_MIN
     *
     * @mbggenerated
     */
    public Integer getFkjeMin() {
        return fkjeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.FKJE_MIN
     *
     * @param fkjeMin the value for BIZ_CODEWFDM.FKJE_MIN
     *
     * @mbggenerated
     */
    public void setFkjeMin(Integer fkjeMin) {
        this.fkjeMin = fkjeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.FKJE_MAX
     *
     * @return the value of BIZ_CODEWFDM.FKJE_MAX
     *
     * @mbggenerated
     */
    public Integer getFkjeMax() {
        return fkjeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.FKJE_MAX
     *
     * @param fkjeMax the value for BIZ_CODEWFDM.FKJE_MAX
     *
     * @mbggenerated
     */
    public void setFkjeMax(Integer fkjeMax) {
        this.fkjeMax = fkjeMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.FKJE_DUT
     *
     * @return the value of BIZ_CODEWFDM.FKJE_DUT
     *
     * @mbggenerated
     */
    public Integer getFkjeDut() {
        return fkjeDut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.FKJE_DUT
     *
     * @param fkjeDut the value for BIZ_CODEWFDM.FKJE_DUT
     *
     * @mbggenerated
     */
    public void setFkjeDut(Integer fkjeDut) {
        this.fkjeDut = fkjeDut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.ZKYS_MIN
     *
     * @return the value of BIZ_CODEWFDM.ZKYS_MIN
     *
     * @mbggenerated
     */
    public String getZkysMin() {
        return zkysMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.ZKYS_MIN
     *
     * @param zkysMin the value for BIZ_CODEWFDM.ZKYS_MIN
     *
     * @mbggenerated
     */
    public void setZkysMin(String zkysMin) {
        this.zkysMin = zkysMin == null ? null : zkysMin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.ZKYS_MAX
     *
     * @return the value of BIZ_CODEWFDM.ZKYS_MAX
     *
     * @mbggenerated
     */
    public String getZkysMax() {
        return zkysMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.ZKYS_MAX
     *
     * @param zkysMax the value for BIZ_CODEWFDM.ZKYS_MAX
     *
     * @mbggenerated
     */
    public void setZkysMax(String zkysMax) {
        this.zkysMax = zkysMax == null ? null : zkysMax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.ZKYS_DUT
     *
     * @return the value of BIZ_CODEWFDM.ZKYS_DUT
     *
     * @mbggenerated
     */
    public String getZkysDut() {
        return zkysDut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.ZKYS_DUT
     *
     * @param zkysDut the value for BIZ_CODEWFDM.ZKYS_DUT
     *
     * @mbggenerated
     */
    public void setZkysDut(String zkysDut) {
        this.zkysDut = zkysDut == null ? null : zkysDut.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.JLSJ_MIN
     *
     * @return the value of BIZ_CODEWFDM.JLSJ_MIN
     *
     * @mbggenerated
     */
    public String getJlsjMin() {
        return jlsjMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.JLSJ_MIN
     *
     * @param jlsjMin the value for BIZ_CODEWFDM.JLSJ_MIN
     *
     * @mbggenerated
     */
    public void setJlsjMin(String jlsjMin) {
        this.jlsjMin = jlsjMin == null ? null : jlsjMin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.JLSJ_MAX
     *
     * @return the value of BIZ_CODEWFDM.JLSJ_MAX
     *
     * @mbggenerated
     */
    public String getJlsjMax() {
        return jlsjMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.JLSJ_MAX
     *
     * @param jlsjMax the value for BIZ_CODEWFDM.JLSJ_MAX
     *
     * @mbggenerated
     */
    public void setJlsjMax(String jlsjMax) {
        this.jlsjMax = jlsjMax == null ? null : jlsjMax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.JLSJ_DUT
     *
     * @return the value of BIZ_CODEWFDM.JLSJ_DUT
     *
     * @mbggenerated
     */
    public String getJlsjDut() {
        return jlsjDut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.JLSJ_DUT
     *
     * @param jlsjDut the value for BIZ_CODEWFDM.JLSJ_DUT
     *
     * @mbggenerated
     */
    public void setJlsjDut(String jlsjDut) {
        this.jlsjDut = jlsjDut == null ? null : jlsjDut.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.QZCSLX
     *
     * @return the value of BIZ_CODEWFDM.QZCSLX
     *
     * @mbggenerated
     */
    public String getQzcslx() {
        return qzcslx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.QZCSLX
     *
     * @param qzcslx the value for BIZ_CODEWFDM.QZCSLX
     *
     * @mbggenerated
     */
    public void setQzcslx(String qzcslx) {
        this.qzcslx = qzcslx == null ? null : qzcslx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.JGBJ
     *
     * @return the value of BIZ_CODEWFDM.JGBJ
     *
     * @mbggenerated
     */
    public String getJgbj() {
        return jgbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.JGBJ
     *
     * @param jgbj the value for BIZ_CODEWFDM.JGBJ
     *
     * @mbggenerated
     */
    public void setJgbj(String jgbj) {
        this.jgbj = jgbj == null ? null : jgbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.FKBJ
     *
     * @return the value of BIZ_CODEWFDM.FKBJ
     *
     * @mbggenerated
     */
    public String getFkbj() {
        return fkbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.FKBJ
     *
     * @param fkbj the value for BIZ_CODEWFDM.FKBJ
     *
     * @mbggenerated
     */
    public void setFkbj(String fkbj) {
        this.fkbj = fkbj == null ? null : fkbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.ZKBJ
     *
     * @return the value of BIZ_CODEWFDM.ZKBJ
     *
     * @mbggenerated
     */
    public String getZkbj() {
        return zkbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.ZKBJ
     *
     * @param zkbj the value for BIZ_CODEWFDM.ZKBJ
     *
     * @mbggenerated
     */
    public void setZkbj(String zkbj) {
        this.zkbj = zkbj == null ? null : zkbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.DXBJ
     *
     * @return the value of BIZ_CODEWFDM.DXBJ
     *
     * @mbggenerated
     */
    public String getDxbj() {
        return dxbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.DXBJ
     *
     * @param dxbj the value for BIZ_CODEWFDM.DXBJ
     *
     * @mbggenerated
     */
    public void setDxbj(String dxbj) {
        this.dxbj = dxbj == null ? null : dxbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.JLBJ
     *
     * @return the value of BIZ_CODEWFDM.JLBJ
     *
     * @mbggenerated
     */
    public String getJlbj() {
        return jlbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.JLBJ
     *
     * @param jlbj the value for BIZ_CODEWFDM.JLBJ
     *
     * @mbggenerated
     */
    public void setJlbj(String jlbj) {
        this.jlbj = jlbj == null ? null : jlbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.CXVBJ
     *
     * @return the value of BIZ_CODEWFDM.CXVBJ
     *
     * @mbggenerated
     */
    public String getCxvbj() {
        return cxvbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.CXVBJ
     *
     * @param cxvbj the value for BIZ_CODEWFDM.CXVBJ
     *
     * @mbggenerated
     */
    public void setCxvbj(String cxvbj) {
        this.cxvbj = cxvbj == null ? null : cxvbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.CXDBJ
     *
     * @return the value of BIZ_CODEWFDM.CXDBJ
     *
     * @mbggenerated
     */
    public String getCxdbj() {
        return cxdbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.CXDBJ
     *
     * @param cxdbj the value for BIZ_CODEWFDM.CXDBJ
     *
     * @mbggenerated
     */
    public void setCxdbj(String cxdbj) {
        this.cxdbj = cxdbj == null ? null : cxdbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.GB
     *
     * @return the value of BIZ_CODEWFDM.GB
     *
     * @mbggenerated
     */
    public String getGb() {
        return gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.GB
     *
     * @param gb the value for BIZ_CODEWFDM.GB
     *
     * @mbggenerated
     */
    public void setGb(String gb) {
        this.gb = gb == null ? null : gb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.YXQS
     *
     * @return the value of BIZ_CODEWFDM.YXQS
     *
     * @mbggenerated
     */
    public Date getYxqs() {
        return yxqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.YXQS
     *
     * @param yxqs the value for BIZ_CODEWFDM.YXQS
     *
     * @mbggenerated
     */
    public void setYxqs(Date yxqs) {
        this.yxqs = yxqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.YXQZ
     *
     * @return the value of BIZ_CODEWFDM.YXQZ
     *
     * @mbggenerated
     */
    public Date getYxqz() {
        return yxqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.YXQZ
     *
     * @param yxqz the value for BIZ_CODEWFDM.YXQZ
     *
     * @mbggenerated
     */
    public void setYxqz(Date yxqz) {
        this.yxqz = yxqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.GLBM
     *
     * @return the value of BIZ_CODEWFDM.GLBM
     *
     * @mbggenerated
     */
    public String getGlbm() {
        return glbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.GLBM
     *
     * @param glbm the value for BIZ_CODEWFDM.GLBM
     *
     * @mbggenerated
     */
    public void setGlbm(String glbm) {
        this.glbm = glbm == null ? null : glbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.CSBJ
     *
     * @return the value of BIZ_CODEWFDM.CSBJ
     *
     * @mbggenerated
     */
    public String getCsbj() {
        return csbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.CSBJ
     *
     * @param csbj the value for BIZ_CODEWFDM.CSBJ
     *
     * @mbggenerated
     */
    public void setCsbj(String csbj) {
        this.csbj = csbj == null ? null : csbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.XH
     *
     * @return the value of BIZ_CODEWFDM.XH
     *
     * @mbggenerated
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.XH
     *
     * @param xh the value for BIZ_CODEWFDM.XH
     *
     * @mbggenerated
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.BJCSBJ
     *
     * @return the value of BIZ_CODEWFDM.BJCSBJ
     *
     * @mbggenerated
     */
    public String getBjcsbj() {
        return bjcsbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.BJCSBJ
     *
     * @param bjcsbj the value for BIZ_CODEWFDM.BJCSBJ
     *
     * @mbggenerated
     */
    public void setBjcsbj(String bjcsbj) {
        this.bjcsbj = bjcsbj == null ? null : bjcsbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_CODEWFDM.XRSJ
     *
     * @return the value of BIZ_CODEWFDM.XRSJ
     *
     * @mbggenerated
     */
    public Date getXrsj() {
        return xrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_CODEWFDM.XRSJ
     *
     * @param xrsj the value for BIZ_CODEWFDM.XRSJ
     *
     * @mbggenerated
     */
    public void setXrsj(Date xrsj) {
        this.xrsj = xrsj;
    }
}