package com.scxd.beans.biz;

import com.scxd.common.JaxbDateAdapter;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.Date;

//@XmlRootElement(name = "viosurveil")
public class BizVioInfo {

    private String id = "";

    private String xh  = "";

    private String cjjg = "";

    private String cjjgmc = "";

    private String fdjh = "";

    private String clsbdh = "";

    private String csys = "";

    private String clpp = "";

    private String tzsh = "";

    private String tzbj = "";

    private Date tzrq;

    private String cjfs = "";

    private String wfbh = "";

    private String jdslb = "";

    private String jdsbh = "";

    private String wsjyw = "";

    private String ryfl = "";

    private String jszh = "";

    private String dabh = "";

    private String fzjg = "";

    private String zjcx = "";

    private String dsr = "";

    private String zsxzqh = "";

    private String zsxxdz = "";

    private String dh = "";

    private String lxfs = "";

    private String clfl = "";

    private String hpzl = "";

    private String hphm = "";

    private String jdcsyr = "";

    private String syxz = "";

    private String jtfs = "";

    private Date wfsj;

    private String wfdd = "";

    private String wfdz = "";

    private String wfxw = "";

    private Short wfjfs;

    private Short fkje;

    private Short scz;

    private Short bzz;

    private Short znj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.ZQMJ
     *
     * @mbggenerated
     */
    private String zqmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.JKFS
     *
     * @mbggenerated
     */
    private String jkfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.FXJG
     *
     * @mbggenerated
     */
    private String fxjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.FXJGMC
     *
     * @mbggenerated
     */
    private String fxjgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CLJG
     *
     * @mbggenerated
     */
    private String cljg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CLJGMC
     *
     * @mbggenerated
     */
    private String cljgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CFZL
     *
     * @mbggenerated
     */
    private String cfzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CLBJ
     *
     * @mbggenerated
     */
    private String clbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CLSJ
     *
     * @mbggenerated
     */
    private Date clsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.JKBJ
     *
     * @mbggenerated
     */
    private String jkbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.JKRQ
     *
     * @mbggenerated
     */
    private Date jkrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.PZBH
     *
     * @mbggenerated
     */
    private String pzbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.JSJQBJ
     *
     * @mbggenerated
     */
    private String jsjqbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.JLLX
     *
     * @mbggenerated
     */
    private String jllx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.LRR
     *
     * @mbggenerated
     */
    private String lrr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.LRSJ
     *
     * @mbggenerated
     */
    private Date lrsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.JBR1
     *
     * @mbggenerated
     */
    private String jbr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.JBR2
     *
     * @mbggenerated
     */
    private String jbr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.SGDJ
     *
     * @mbggenerated
     */
    private String sgdj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CLDXBJ
     *
     * @mbggenerated
     */
    private String cldxbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.XXLY
     *
     * @mbggenerated
     */
    private String xxly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.XRMS
     *
     * @mbggenerated
     */
    private String xrms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.JSJG
     *
     * @mbggenerated
     */
    private String jsjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.FSJG
     *
     * @mbggenerated
     */
    private String fsjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.YSZNJ
     *
     * @mbggenerated
     */
    private String ysznj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CJSJ
     *
     * @mbggenerated
     */
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CXLY
     *
     * @mbggenerated
     */
    private String cxly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.DLDM
     *
     * @mbggenerated
     */
    private String dldm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.SGLY
     *
     * @mbggenerated
     */
    private String sgly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CLYT
     *
     * @mbggenerated
     */
    private String clyt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.ZKYS
     *
     * @mbggenerated
     */
    private String zkys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.JLTS
     *
     * @mbggenerated
     */
    private String jlts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CFLB
     *
     * @mbggenerated
     */
    private String cflb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.CFBH
     *
     * @mbggenerated
     */
    private String cfbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_VIO_INFO.JBR
     *
     * @mbggenerated
     */
    private String jbr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.ID
     *
     * @return the value of BIZ_VIO_INFO.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.ID
     *
     * @param id the value for BIZ_VIO_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.XH
     *
     * @return the value of BIZ_VIO_INFO.XH
     *
     * @mbggenerated
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.XH
     *
     * @param xh the value for BIZ_VIO_INFO.XH
     *
     * @mbggenerated
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CJJG
     *
     * @return the value of BIZ_VIO_INFO.CJJG
     *
     * @mbggenerated
     */
    public String getCjjg() {
        return cjjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CJJG
     *
     * @param cjjg the value for BIZ_VIO_INFO.CJJG
     *
     * @mbggenerated
     */
    public void setCjjg(String cjjg) {
        this.cjjg = cjjg == null ? null : cjjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CJJGMC
     *
     * @return the value of BIZ_VIO_INFO.CJJGMC
     *
     * @mbggenerated
     */
    public String getCjjgmc() {
        return cjjgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CJJGMC
     *
     * @param cjjgmc the value for BIZ_VIO_INFO.CJJGMC
     *
     * @mbggenerated
     */
    public void setCjjgmc(String cjjgmc) {
        this.cjjgmc = cjjgmc == null ? null : cjjgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.FDJH
     *
     * @return the value of BIZ_VIO_INFO.FDJH
     *
     * @mbggenerated
     */
    public String getFdjh() {
        return fdjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.FDJH
     *
     * @param fdjh the value for BIZ_VIO_INFO.FDJH
     *
     * @mbggenerated
     */
    public void setFdjh(String fdjh) {
        this.fdjh = fdjh == null ? null : fdjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CLSBDH
     *
     * @return the value of BIZ_VIO_INFO.CLSBDH
     *
     * @mbggenerated
     */
    public String getClsbdh() {
        return clsbdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CLSBDH
     *
     * @param clsbdh the value for BIZ_VIO_INFO.CLSBDH
     *
     * @mbggenerated
     */
    public void setClsbdh(String clsbdh) {
        this.clsbdh = clsbdh == null ? null : clsbdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CSYS
     *
     * @return the value of BIZ_VIO_INFO.CSYS
     *
     * @mbggenerated
     */
    public String getCsys() {
        return csys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CSYS
     *
     * @param csys the value for BIZ_VIO_INFO.CSYS
     *
     * @mbggenerated
     */
    public void setCsys(String csys) {
        this.csys = csys == null ? null : csys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CLPP
     *
     * @return the value of BIZ_VIO_INFO.CLPP
     *
     * @mbggenerated
     */
    public String getClpp() {
        return clpp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CLPP
     *
     * @param clpp the value for BIZ_VIO_INFO.CLPP
     *
     * @mbggenerated
     */
    public void setClpp(String clpp) {
        this.clpp = clpp == null ? null : clpp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.TZSH
     *
     * @return the value of BIZ_VIO_INFO.TZSH
     *
     * @mbggenerated
     */
    public String getTzsh() {
        return tzsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.TZSH
     *
     * @param tzsh the value for BIZ_VIO_INFO.TZSH
     *
     * @mbggenerated
     */
    public void setTzsh(String tzsh) {
        this.tzsh = tzsh == null ? null : tzsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.TZBJ
     *
     * @return the value of BIZ_VIO_INFO.TZBJ
     *
     * @mbggenerated
     */
    public String getTzbj() {
        return tzbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.TZBJ
     *
     * @param tzbj the value for BIZ_VIO_INFO.TZBJ
     *
     * @mbggenerated
     */
    public void setTzbj(String tzbj) {
        this.tzbj = tzbj == null ? null : tzbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.TZRQ
     *
     * @return the value of BIZ_VIO_INFO.TZRQ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getTzrq() {
        return tzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.TZRQ
     *
     * @param tzrq the value for BIZ_VIO_INFO.TZRQ
     *
     * @mbggenerated
     */
    public void setTzrq(Date tzrq) {
        this.tzrq = tzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CJFS
     *
     * @return the value of BIZ_VIO_INFO.CJFS
     *
     * @mbggenerated
     */
    public String getCjfs() {
        return cjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CJFS
     *
     * @param cjfs the value for BIZ_VIO_INFO.CJFS
     *
     * @mbggenerated
     */
    public void setCjfs(String cjfs) {
        this.cjfs = cjfs == null ? null : cjfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.WFBH
     *
     * @return the value of BIZ_VIO_INFO.WFBH
     *
     * @mbggenerated
     */
    public String getWfbh() {
        return wfbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.WFBH
     *
     * @param wfbh the value for BIZ_VIO_INFO.WFBH
     *
     * @mbggenerated
     */
    public void setWfbh(String wfbh) {
        this.wfbh = wfbh == null ? null : wfbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JDSLB
     *
     * @return the value of BIZ_VIO_INFO.JDSLB
     *
     * @mbggenerated
     */
    public String getJdslb() {
        return jdslb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JDSLB
     *
     * @param jdslb the value for BIZ_VIO_INFO.JDSLB
     *
     * @mbggenerated
     */
    public void setJdslb(String jdslb) {
        this.jdslb = jdslb == null ? null : jdslb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JDSBH
     *
     * @return the value of BIZ_VIO_INFO.JDSBH
     *
     * @mbggenerated
     */
    public String getJdsbh() {
        return jdsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JDSBH
     *
     * @param jdsbh the value for BIZ_VIO_INFO.JDSBH
     *
     * @mbggenerated
     */
    public void setJdsbh(String jdsbh) {
        this.jdsbh = jdsbh == null ? null : jdsbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.WSJYW
     *
     * @return the value of BIZ_VIO_INFO.WSJYW
     *
     * @mbggenerated
     */
    public String getWsjyw() {
        return wsjyw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.WSJYW
     *
     * @param wsjyw the value for BIZ_VIO_INFO.WSJYW
     *
     * @mbggenerated
     */
    public void setWsjyw(String wsjyw) {
        this.wsjyw = wsjyw == null ? null : wsjyw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.RYFL
     *
     * @return the value of BIZ_VIO_INFO.RYFL
     *
     * @mbggenerated
     */
    public String getRyfl() {
        return ryfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.RYFL
     *
     * @param ryfl the value for BIZ_VIO_INFO.RYFL
     *
     * @mbggenerated
     */
    public void setRyfl(String ryfl) {
        this.ryfl = ryfl == null ? null : ryfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JSZH
     *
     * @return the value of BIZ_VIO_INFO.JSZH
     *
     * @mbggenerated
     */
    public String getJszh() {
        return jszh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JSZH
     *
     * @param jszh the value for BIZ_VIO_INFO.JSZH
     *
     * @mbggenerated
     */
    public void setJszh(String jszh) {
        this.jszh = jszh == null ? null : jszh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.DABH
     *
     * @return the value of BIZ_VIO_INFO.DABH
     *
     * @mbggenerated
     */
    public String getDabh() {
        return dabh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.DABH
     *
     * @param dabh the value for BIZ_VIO_INFO.DABH
     *
     * @mbggenerated
     */
    public void setDabh(String dabh) {
        this.dabh = dabh == null ? null : dabh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.FZJG
     *
     * @return the value of BIZ_VIO_INFO.FZJG
     *
     * @mbggenerated
     */
    public String getFzjg() {
        return fzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.FZJG
     *
     * @param fzjg the value for BIZ_VIO_INFO.FZJG
     *
     * @mbggenerated
     */
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg == null ? null : fzjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.ZJCX
     *
     * @return the value of BIZ_VIO_INFO.ZJCX
     *
     * @mbggenerated
     */
    public String getZjcx() {
        return zjcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.ZJCX
     *
     * @param zjcx the value for BIZ_VIO_INFO.ZJCX
     *
     * @mbggenerated
     */
    public void setZjcx(String zjcx) {
        this.zjcx = zjcx == null ? null : zjcx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.DSR
     *
     * @return the value of BIZ_VIO_INFO.DSR
     *
     * @mbggenerated
     */
    public String getDsr() {
        return dsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.DSR
     *
     * @param dsr the value for BIZ_VIO_INFO.DSR
     *
     * @mbggenerated
     */
    public void setDsr(String dsr) {
        this.dsr = dsr == null ? null : dsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.ZSXZQH
     *
     * @return the value of BIZ_VIO_INFO.ZSXZQH
     *
     * @mbggenerated
     */
    public String getZsxzqh() {
        return zsxzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.ZSXZQH
     *
     * @param zsxzqh the value for BIZ_VIO_INFO.ZSXZQH
     *
     * @mbggenerated
     */
    public void setZsxzqh(String zsxzqh) {
        this.zsxzqh = zsxzqh == null ? null : zsxzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.ZSXXDZ
     *
     * @return the value of BIZ_VIO_INFO.ZSXXDZ
     *
     * @mbggenerated
     */
    public String getZsxxdz() {
        return zsxxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.ZSXXDZ
     *
     * @param zsxxdz the value for BIZ_VIO_INFO.ZSXXDZ
     *
     * @mbggenerated
     */
    public void setZsxxdz(String zsxxdz) {
        this.zsxxdz = zsxxdz == null ? null : zsxxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.DH
     *
     * @return the value of BIZ_VIO_INFO.DH
     *
     * @mbggenerated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.DH
     *
     * @param dh the value for BIZ_VIO_INFO.DH
     *
     * @mbggenerated
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.LXFS
     *
     * @return the value of BIZ_VIO_INFO.LXFS
     *
     * @mbggenerated
     */
    public String getLxfs() {
        return lxfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.LXFS
     *
     * @param lxfs the value for BIZ_VIO_INFO.LXFS
     *
     * @mbggenerated
     */
    public void setLxfs(String lxfs) {
        this.lxfs = lxfs == null ? null : lxfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CLFL
     *
     * @return the value of BIZ_VIO_INFO.CLFL
     *
     * @mbggenerated
     */
    public String getClfl() {
        return clfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CLFL
     *
     * @param clfl the value for BIZ_VIO_INFO.CLFL
     *
     * @mbggenerated
     */
    public void setClfl(String clfl) {
        this.clfl = clfl == null ? null : clfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.HPZL
     *
     * @return the value of BIZ_VIO_INFO.HPZL
     *
     * @mbggenerated
     */
    public String getHpzl() {
        return hpzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.HPZL
     *
     * @param hpzl the value for BIZ_VIO_INFO.HPZL
     *
     * @mbggenerated
     */
    public void setHpzl(String hpzl) {
        this.hpzl = hpzl == null ? null : hpzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.HPHM
     *
     * @return the value of BIZ_VIO_INFO.HPHM
     *
     * @mbggenerated
     */
    public String getHphm() {
        return hphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.HPHM
     *
     * @param hphm the value for BIZ_VIO_INFO.HPHM
     *
     * @mbggenerated
     */
    public void setHphm(String hphm) {
        this.hphm = hphm == null ? null : hphm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JDCSYR
     *
     * @return the value of BIZ_VIO_INFO.JDCSYR
     *
     * @mbggenerated
     */
    public String getJdcsyr() {
        return jdcsyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JDCSYR
     *
     * @param jdcsyr the value for BIZ_VIO_INFO.JDCSYR
     *
     * @mbggenerated
     */
    public void setJdcsyr(String jdcsyr) {
        this.jdcsyr = jdcsyr == null ? null : jdcsyr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.SYXZ
     *
     * @return the value of BIZ_VIO_INFO.SYXZ
     *
     * @mbggenerated
     */
    public String getSyxz() {
        return syxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.SYXZ
     *
     * @param syxz the value for BIZ_VIO_INFO.SYXZ
     *
     * @mbggenerated
     */
    public void setSyxz(String syxz) {
        this.syxz = syxz == null ? null : syxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JTFS
     *
     * @return the value of BIZ_VIO_INFO.JTFS
     *
     * @mbggenerated
     */
    public String getJtfs() {
        return jtfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JTFS
     *
     * @param jtfs the value for BIZ_VIO_INFO.JTFS
     *
     * @mbggenerated
     */
    public void setJtfs(String jtfs) {
        this.jtfs = jtfs == null ? null : jtfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.WFSJ
     *
     * @return the value of BIZ_VIO_INFO.WFSJ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getWfsj() {
        return wfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.WFSJ
     *
     * @param wfsj the value for BIZ_VIO_INFO.WFSJ
     *
     * @mbggenerated
     */
    public void setWfsj(Date wfsj) {
        this.wfsj = wfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.WFDD
     *
     * @return the value of BIZ_VIO_INFO.WFDD
     *
     * @mbggenerated
     */
    public String getWfdd() {
        return wfdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.WFDD
     *
     * @param wfdd the value for BIZ_VIO_INFO.WFDD
     *
     * @mbggenerated
     */
    public void setWfdd(String wfdd) {
        this.wfdd = wfdd == null ? null : wfdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.WFDZ
     *
     * @return the value of BIZ_VIO_INFO.WFDZ
     *
     * @mbggenerated
     */
    public String getWfdz() {
        return wfdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.WFDZ
     *
     * @param wfdz the value for BIZ_VIO_INFO.WFDZ
     *
     * @mbggenerated
     */
    public void setWfdz(String wfdz) {
        this.wfdz = wfdz == null ? null : wfdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.WFXW
     *
     * @return the value of BIZ_VIO_INFO.WFXW
     *
     * @mbggenerated
     */
    public String getWfxw() {
        return wfxw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.WFXW
     *
     * @param wfxw the value for BIZ_VIO_INFO.WFXW
     *
     * @mbggenerated
     */
    public void setWfxw(String wfxw) {
        this.wfxw = wfxw == null ? null : wfxw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.WFJFS
     *
     * @return the value of BIZ_VIO_INFO.WFJFS
     *
     * @mbggenerated
     */
    public Short getWfjfs() {
        return wfjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.WFJFS
     *
     * @param wfjfs the value for BIZ_VIO_INFO.WFJFS
     *
     * @mbggenerated
     */
    public void setWfjfs(Short wfjfs) {
        this.wfjfs = wfjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.FKJE
     *
     * @return the value of BIZ_VIO_INFO.FKJE
     *
     * @mbggenerated
     */
    public Short getFkje() {
        return fkje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.FKJE
     *
     * @param fkje the value for BIZ_VIO_INFO.FKJE
     *
     * @mbggenerated
     */
    public void setFkje(Short fkje) {
        this.fkje = fkje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.SCZ
     *
     * @return the value of BIZ_VIO_INFO.SCZ
     *
     * @mbggenerated
     */
    public Short getScz() {
        return scz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.SCZ
     *
     * @param scz the value for BIZ_VIO_INFO.SCZ
     *
     * @mbggenerated
     */
    public void setScz(Short scz) {
        this.scz = scz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.BZZ
     *
     * @return the value of BIZ_VIO_INFO.BZZ
     *
     * @mbggenerated
     */
    public Short getBzz() {
        return bzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.BZZ
     *
     * @param bzz the value for BIZ_VIO_INFO.BZZ
     *
     * @mbggenerated
     */
    public void setBzz(Short bzz) {
        this.bzz = bzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.ZNJ
     *
     * @return the value of BIZ_VIO_INFO.ZNJ
     *
     * @mbggenerated
     */
    public Short getZnj() {
        return znj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.ZNJ
     *
     * @param znj the value for BIZ_VIO_INFO.ZNJ
     *
     * @mbggenerated
     */
    public void setZnj(Short znj) {
        this.znj = znj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.ZQMJ
     *
     * @return the value of BIZ_VIO_INFO.ZQMJ
     *
     * @mbggenerated
     */
    public String getZqmj() {
        return zqmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.ZQMJ
     *
     * @param zqmj the value for BIZ_VIO_INFO.ZQMJ
     *
     * @mbggenerated
     */
    public void setZqmj(String zqmj) {
        this.zqmj = zqmj == null ? null : zqmj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JKFS
     *
     * @return the value of BIZ_VIO_INFO.JKFS
     *
     * @mbggenerated
     */
    public String getJkfs() {
        return jkfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JKFS
     *
     * @param jkfs the value for BIZ_VIO_INFO.JKFS
     *
     * @mbggenerated
     */
    public void setJkfs(String jkfs) {
        this.jkfs = jkfs == null ? null : jkfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.FXJG
     *
     * @return the value of BIZ_VIO_INFO.FXJG
     *
     * @mbggenerated
     */
    public String getFxjg() {
        return fxjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.FXJG
     *
     * @param fxjg the value for BIZ_VIO_INFO.FXJG
     *
     * @mbggenerated
     */
    public void setFxjg(String fxjg) {
        this.fxjg = fxjg == null ? null : fxjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.FXJGMC
     *
     * @return the value of BIZ_VIO_INFO.FXJGMC
     *
     * @mbggenerated
     */
    public String getFxjgmc() {
        return fxjgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.FXJGMC
     *
     * @param fxjgmc the value for BIZ_VIO_INFO.FXJGMC
     *
     * @mbggenerated
     */
    public void setFxjgmc(String fxjgmc) {
        this.fxjgmc = fxjgmc == null ? null : fxjgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CLJG
     *
     * @return the value of BIZ_VIO_INFO.CLJG
     *
     * @mbggenerated
     */
    public String getCljg() {
        return cljg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CLJG
     *
     * @param cljg the value for BIZ_VIO_INFO.CLJG
     *
     * @mbggenerated
     */
    public void setCljg(String cljg) {
        this.cljg = cljg == null ? null : cljg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CLJGMC
     *
     * @return the value of BIZ_VIO_INFO.CLJGMC
     *
     * @mbggenerated
     */
    public String getCljgmc() {
        return cljgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CLJGMC
     *
     * @param cljgmc the value for BIZ_VIO_INFO.CLJGMC
     *
     * @mbggenerated
     */
    public void setCljgmc(String cljgmc) {
        this.cljgmc = cljgmc == null ? null : cljgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CFZL
     *
     * @return the value of BIZ_VIO_INFO.CFZL
     *
     * @mbggenerated
     */
    public String getCfzl() {
        return cfzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CFZL
     *
     * @param cfzl the value for BIZ_VIO_INFO.CFZL
     *
     * @mbggenerated
     */
    public void setCfzl(String cfzl) {
        this.cfzl = cfzl == null ? null : cfzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CLBJ
     *
     * @return the value of BIZ_VIO_INFO.CLBJ
     *
     * @mbggenerated
     */
    public String getClbj() {
        return clbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CLBJ
     *
     * @param clbj the value for BIZ_VIO_INFO.CLBJ
     *
     * @mbggenerated
     */
    public void setClbj(String clbj) {
        this.clbj = clbj == null ? null : clbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CLSJ
     *
     * @return the value of BIZ_VIO_INFO.CLSJ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getClsj() {
        return clsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CLSJ
     *
     * @param clsj the value for BIZ_VIO_INFO.CLSJ
     *
     * @mbggenerated
     */
    public void setClsj(Date clsj) {
        this.clsj = clsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JKBJ
     *
     * @return the value of BIZ_VIO_INFO.JKBJ
     *
     * @mbggenerated
     */
    public String getJkbj() {
        return jkbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JKBJ
     *
     * @param jkbj the value for BIZ_VIO_INFO.JKBJ
     *
     * @mbggenerated
     */
    public void setJkbj(String jkbj) {
        this.jkbj = jkbj == null ? null : jkbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JKRQ
     *
     * @return the value of BIZ_VIO_INFO.JKRQ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getJkrq() {
        return jkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JKRQ
     *
     * @param jkrq the value for BIZ_VIO_INFO.JKRQ
     *
     * @mbggenerated
     */
    public void setJkrq(Date jkrq) {
        this.jkrq = jkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.PZBH
     *
     * @return the value of BIZ_VIO_INFO.PZBH
     *
     * @mbggenerated
     */
    public String getPzbh() {
        return pzbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.PZBH
     *
     * @param pzbh the value for BIZ_VIO_INFO.PZBH
     *
     * @mbggenerated
     */
    public void setPzbh(String pzbh) {
        this.pzbh = pzbh == null ? null : pzbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JSJQBJ
     *
     * @return the value of BIZ_VIO_INFO.JSJQBJ
     *
     * @mbggenerated
     */
    public String getJsjqbj() {
        return jsjqbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JSJQBJ
     *
     * @param jsjqbj the value for BIZ_VIO_INFO.JSJQBJ
     *
     * @mbggenerated
     */
    public void setJsjqbj(String jsjqbj) {
        this.jsjqbj = jsjqbj == null ? null : jsjqbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JLLX
     *
     * @return the value of BIZ_VIO_INFO.JLLX
     *
     * @mbggenerated
     */
    public String getJllx() {
        return jllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JLLX
     *
     * @param jllx the value for BIZ_VIO_INFO.JLLX
     *
     * @mbggenerated
     */
    public void setJllx(String jllx) {
        this.jllx = jllx == null ? null : jllx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.LRR
     *
     * @return the value of BIZ_VIO_INFO.LRR
     *
     * @mbggenerated
     */
    public String getLrr() {
        return lrr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.LRR
     *
     * @param lrr the value for BIZ_VIO_INFO.LRR
     *
     * @mbggenerated
     */
    public void setLrr(String lrr) {
        this.lrr = lrr == null ? null : lrr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.LRSJ
     *
     * @return the value of BIZ_VIO_INFO.LRSJ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.LRSJ
     *
     * @param lrsj the value for BIZ_VIO_INFO.LRSJ
     *
     * @mbggenerated
     */
    public void setLrsj(Date lrsj) {
        this.lrsj = lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JBR1
     *
     * @return the value of BIZ_VIO_INFO.JBR1
     *
     * @mbggenerated
     */
    public String getJbr1() {
        return jbr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JBR1
     *
     * @param jbr1 the value for BIZ_VIO_INFO.JBR1
     *
     * @mbggenerated
     */
    public void setJbr1(String jbr1) {
        this.jbr1 = jbr1 == null ? null : jbr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JBR2
     *
     * @return the value of BIZ_VIO_INFO.JBR2
     *
     * @mbggenerated
     */
    public String getJbr2() {
        return jbr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JBR2
     *
     * @param jbr2 the value for BIZ_VIO_INFO.JBR2
     *
     * @mbggenerated
     */
    public void setJbr2(String jbr2) {
        this.jbr2 = jbr2 == null ? null : jbr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.SGDJ
     *
     * @return the value of BIZ_VIO_INFO.SGDJ
     *
     * @mbggenerated
     */
    public String getSgdj() {
        return sgdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.SGDJ
     *
     * @param sgdj the value for BIZ_VIO_INFO.SGDJ
     *
     * @mbggenerated
     */
    public void setSgdj(String sgdj) {
        this.sgdj = sgdj == null ? null : sgdj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CLDXBJ
     *
     * @return the value of BIZ_VIO_INFO.CLDXBJ
     *
     * @mbggenerated
     */
    public String getCldxbj() {
        return cldxbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CLDXBJ
     *
     * @param cldxbj the value for BIZ_VIO_INFO.CLDXBJ
     *
     * @mbggenerated
     */
    public void setCldxbj(String cldxbj) {
        this.cldxbj = cldxbj == null ? null : cldxbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.XXLY
     *
     * @return the value of BIZ_VIO_INFO.XXLY
     *
     * @mbggenerated
     */
    public String getXxly() {
        return xxly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.XXLY
     *
     * @param xxly the value for BIZ_VIO_INFO.XXLY
     *
     * @mbggenerated
     */
    public void setXxly(String xxly) {
        this.xxly = xxly == null ? null : xxly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.XRMS
     *
     * @return the value of BIZ_VIO_INFO.XRMS
     *
     * @mbggenerated
     */
    public String getXrms() {
        return xrms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.XRMS
     *
     * @param xrms the value for BIZ_VIO_INFO.XRMS
     *
     * @mbggenerated
     */
    public void setXrms(String xrms) {
        this.xrms = xrms == null ? null : xrms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JSJG
     *
     * @return the value of BIZ_VIO_INFO.JSJG
     *
     * @mbggenerated
     */
    public String getJsjg() {
        return jsjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JSJG
     *
     * @param jsjg the value for BIZ_VIO_INFO.JSJG
     *
     * @mbggenerated
     */
    public void setJsjg(String jsjg) {
        this.jsjg = jsjg == null ? null : jsjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.FSJG
     *
     * @return the value of BIZ_VIO_INFO.FSJG
     *
     * @mbggenerated
     */
    public String getFsjg() {
        return fsjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.FSJG
     *
     * @param fsjg the value for BIZ_VIO_INFO.FSJG
     *
     * @mbggenerated
     */
    public void setFsjg(String fsjg) {
        this.fsjg = fsjg == null ? null : fsjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.GXSJ
     *
     * @return the value of BIZ_VIO_INFO.GXSJ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.GXSJ
     *
     * @param gxsj the value for BIZ_VIO_INFO.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.BZ
     *
     * @return the value of BIZ_VIO_INFO.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.BZ
     *
     * @param bz the value for BIZ_VIO_INFO.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.YSZNJ
     *
     * @return the value of BIZ_VIO_INFO.YSZNJ
     *
     * @mbggenerated
     */
    public String getYsznj() {
        return ysznj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.YSZNJ
     *
     * @param ysznj the value for BIZ_VIO_INFO.YSZNJ
     *
     * @mbggenerated
     */
    public void setYsznj(String ysznj) {
        this.ysznj = ysznj == null ? null : ysznj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CJSJ
     *
     * @return the value of BIZ_VIO_INFO.CJSJ
     *
     * @mbggenerated
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CJSJ
     *
     * @param cjsj the value for BIZ_VIO_INFO.CJSJ
     *
     * @mbggenerated
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CXLY
     *
     * @return the value of BIZ_VIO_INFO.CXLY
     *
     * @mbggenerated
     */
    public String getCxly() {
        return cxly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CXLY
     *
     * @param cxly the value for BIZ_VIO_INFO.CXLY
     *
     * @mbggenerated
     */
    public void setCxly(String cxly) {
        this.cxly = cxly == null ? null : cxly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.DLDM
     *
     * @return the value of BIZ_VIO_INFO.DLDM
     *
     * @mbggenerated
     */
    public String getDldm() {
        return dldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.DLDM
     *
     * @param dldm the value for BIZ_VIO_INFO.DLDM
     *
     * @mbggenerated
     */
    public void setDldm(String dldm) {
        this.dldm = dldm == null ? null : dldm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.SGLY
     *
     * @return the value of BIZ_VIO_INFO.SGLY
     *
     * @mbggenerated
     */
    public String getSgly() {
        return sgly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.SGLY
     *
     * @param sgly the value for BIZ_VIO_INFO.SGLY
     *
     * @mbggenerated
     */
    public void setSgly(String sgly) {
        this.sgly = sgly == null ? null : sgly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CLYT
     *
     * @return the value of BIZ_VIO_INFO.CLYT
     *
     * @mbggenerated
     */
    public String getClyt() {
        return clyt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CLYT
     *
     * @param clyt the value for BIZ_VIO_INFO.CLYT
     *
     * @mbggenerated
     */
    public void setClyt(String clyt) {
        this.clyt = clyt == null ? null : clyt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.ZKYS
     *
     * @return the value of BIZ_VIO_INFO.ZKYS
     *
     * @mbggenerated
     */
    public String getZkys() {
        return zkys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.ZKYS
     *
     * @param zkys the value for BIZ_VIO_INFO.ZKYS
     *
     * @mbggenerated
     */
    public void setZkys(String zkys) {
        this.zkys = zkys == null ? null : zkys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JLTS
     *
     * @return the value of BIZ_VIO_INFO.JLTS
     *
     * @mbggenerated
     */
    public String getJlts() {
        return jlts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JLTS
     *
     * @param jlts the value for BIZ_VIO_INFO.JLTS
     *
     * @mbggenerated
     */
    public void setJlts(String jlts) {
        this.jlts = jlts == null ? null : jlts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CFLB
     *
     * @return the value of BIZ_VIO_INFO.CFLB
     *
     * @mbggenerated
     */
    public String getCflb() {
        return cflb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CFLB
     *
     * @param cflb the value for BIZ_VIO_INFO.CFLB
     *
     * @mbggenerated
     */
    public void setCflb(String cflb) {
        this.cflb = cflb == null ? null : cflb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.CFBH
     *
     * @return the value of BIZ_VIO_INFO.CFBH
     *
     * @mbggenerated
     */
    public String getCfbh() {
        return cfbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.CFBH
     *
     * @param cfbh the value for BIZ_VIO_INFO.CFBH
     *
     * @mbggenerated
     */
    public void setCfbh(String cfbh) {
        this.cfbh = cfbh == null ? null : cfbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VIO_INFO.JBR
     *
     * @return the value of BIZ_VIO_INFO.JBR
     *
     * @mbggenerated
     */
    public String getJbr() {
        return jbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VIO_INFO.JBR
     *
     * @param jbr the value for BIZ_VIO_INFO.JBR
     *
     * @mbggenerated
     */
    public void setJbr(String jbr) {
        this.jbr = jbr == null ? null : jbr.trim();
    }

    @Override
    public String toString() {
        return "BizVioInfo{" +
                "id='" + id + '\'' +
                ", xh='" + xh + '\'' +
                ", cjjg='" + cjjg + '\'' +
                ", cjjgmc='" + cjjgmc + '\'' +
                ", fdjh='" + fdjh + '\'' +
                ", clsbdh='" + clsbdh + '\'' +
                ", csys='" + csys + '\'' +
                ", clpp='" + clpp + '\'' +
                ", tzsh='" + tzsh + '\'' +
                ", tzbj='" + tzbj + '\'' +
                ", tzrq=" + tzrq +
                ", cjfs='" + cjfs + '\'' +
                ", wfbh='" + wfbh + '\'' +
                ", jdslb='" + jdslb + '\'' +
                ", jdsbh='" + jdsbh + '\'' +
                ", wsjyw='" + wsjyw + '\'' +
                ", ryfl='" + ryfl + '\'' +
                ", jszh='" + jszh + '\'' +
                ", dabh='" + dabh + '\'' +
                ", fzjg='" + fzjg + '\'' +
                ", zjcx='" + zjcx + '\'' +
                ", dsr='" + dsr + '\'' +
                ", zsxzqh='" + zsxzqh + '\'' +
                ", zsxxdz='" + zsxxdz + '\'' +
                ", dh='" + dh + '\'' +
                ", lxfs='" + lxfs + '\'' +
                ", clfl='" + clfl + '\'' +
                ", hpzl='" + hpzl + '\'' +
                ", hphm='" + hphm + '\'' +
                ", jdcsyr='" + jdcsyr + '\'' +
                ", syxz='" + syxz + '\'' +
                ", jtfs='" + jtfs + '\'' +
                ", wfsj=" + wfsj +
                ", wfdd='" + wfdd + '\'' +
                ", wfdz='" + wfdz + '\'' +
                ", wfxw='" + wfxw + '\'' +
                ", wfjfs=" + wfjfs +
                ", fkje=" + fkje +
                ", scz=" + scz +
                ", bzz=" + bzz +
                ", znj=" + znj +
                ", zqmj='" + zqmj + '\'' +
                ", jkfs='" + jkfs + '\'' +
                ", fxjg='" + fxjg + '\'' +
                ", fxjgmc='" + fxjgmc + '\'' +
                ", cljg='" + cljg + '\'' +
                ", cljgmc='" + cljgmc + '\'' +
                ", cfzl='" + cfzl + '\'' +
                ", clbj='" + clbj + '\'' +
                ", clsj=" + clsj +
                ", jkbj='" + jkbj + '\'' +
                ", jkrq=" + jkrq +
                ", pzbh='" + pzbh + '\'' +
                ", jsjqbj='" + jsjqbj + '\'' +
                ", jllx='" + jllx + '\'' +
                ", lrr='" + lrr + '\'' +
                ", lrsj=" + lrsj +
                ", jbr1='" + jbr1 + '\'' +
                ", jbr2='" + jbr2 + '\'' +
                ", sgdj='" + sgdj + '\'' +
                ", cldxbj='" + cldxbj + '\'' +
                ", xxly='" + xxly + '\'' +
                ", xrms='" + xrms + '\'' +
                ", jsjg='" + jsjg + '\'' +
                ", fsjg='" + fsjg + '\'' +
                ", gxsj=" + gxsj +
                ", bz='" + bz + '\'' +
                ", ysznj='" + ysznj + '\'' +
                ", cjsj=" + cjsj +
                ", cxly='" + cxly + '\'' +
                ", dldm='" + dldm + '\'' +
                ", sgly='" + sgly + '\'' +
                ", clyt='" + clyt + '\'' +
                ", zkys='" + zkys + '\'' +
                ", jlts='" + jlts + '\'' +
                ", cflb='" + cflb + '\'' +
                ", cfbh='" + cfbh + '\'' +
                ", jbr='" + jbr + '\'' +
                '}';
    }
}