package com.scxd.beans.pojo.test;

import java.util.Date;

public class BizDrvInfoBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.SFZMMC
     *
     * @mbggenerated
     */
    private String sfzmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.SFZMHM
     *
     * @mbggenerated
     */
    private String sfzmhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.HMCD
     *
     * @mbggenerated
     */
    private String hmcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.XM
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.XB
     *
     * @mbggenerated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.CSRQ
     *
     * @mbggenerated
     */
    private Date csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.GJ
     *
     * @mbggenerated
     */
    private String gj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.DJZSXZQH
     *
     * @mbggenerated
     */
    private String djzsxzqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.DJZSXXDZ
     *
     * @mbggenerated
     */
    private String djzsxxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.LXZSXZQH
     *
     * @mbggenerated
     */
    private String lxzsxzqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.LXZSXXDZ
     *
     * @mbggenerated
     */
    private String lxzsxxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.LXZSYZBM
     *
     * @mbggenerated
     */
    private String lxzsyzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.LXDH
     *
     * @mbggenerated
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.SJHM
     *
     * @mbggenerated
     */
    private String sjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.DZYX
     *
     * @mbggenerated
     */
    private String dzyx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.DABH
     *
     * @mbggenerated
     */
    private String dabh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.ZJCX
     *
     * @mbggenerated
     */
    private String zjcx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.LJJF
     *
     * @mbggenerated
     */
    private Short ljjf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.ZT
     *
     * @mbggenerated
     */
    private String zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.CCLZRQ
     *
     * @mbggenerated
     */
    private Date cclzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.JZQX
     *
     * @mbggenerated
     */
    private Date jzqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.SYRQ
     *
     * @mbggenerated
     */
    private Date syrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.YXQS
     *
     * @mbggenerated
     */
    private Date yxqs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.YXQZ
     *
     * @mbggenerated
     */
    private Date yxqz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.XZQH
     *
     * @mbggenerated
     */
    private String xzqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.ZZZM
     *
     * @mbggenerated
     */
    private String zzzm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.GXSJ
     *
     * @mbggenerated
     */
    private Date gxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.ZXBH
     *
     * @mbggenerated
     */
    private String zxbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.FZJG
     *
     * @mbggenerated
     */
    private String fzjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.ZHQFRQ
     *
     * @mbggenerated
     */
    private Date zhqfrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.MFQFRQ
     *
     * @mbggenerated
     */
    private Date mfqfrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.XYQFRQ
     *
     * @mbggenerated
     */
    private Date xyqfrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.SFCF
     *
     * @mbggenerated
     */
    private String sfcf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.YQWSY
     *
     * @mbggenerated
     */
    private String yqwsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.YQWHZ
     *
     * @mbggenerated
     */
    private String yqwhz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_DRV_INFO.XRSJ
     *
     * @mbggenerated
     */
    private Date xrsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.ID
     *
     * @return the value of BIZ_DRV_INFO.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.ID
     *
     * @param id the value for BIZ_DRV_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.SFZMMC
     *
     * @return the value of BIZ_DRV_INFO.SFZMMC
     *
     * @mbggenerated
     */
    public String getSfzmmc() {
        return sfzmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.SFZMMC
     *
     * @param sfzmmc the value for BIZ_DRV_INFO.SFZMMC
     *
     * @mbggenerated
     */
    public void setSfzmmc(String sfzmmc) {
        this.sfzmmc = sfzmmc == null ? null : sfzmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.SFZMHM
     *
     * @return the value of BIZ_DRV_INFO.SFZMHM
     *
     * @mbggenerated
     */
    public String getSfzmhm() {
        return sfzmhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.SFZMHM
     *
     * @param sfzmhm the value for BIZ_DRV_INFO.SFZMHM
     *
     * @mbggenerated
     */
    public void setSfzmhm(String sfzmhm) {
        this.sfzmhm = sfzmhm == null ? null : sfzmhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.HMCD
     *
     * @return the value of BIZ_DRV_INFO.HMCD
     *
     * @mbggenerated
     */
    public String getHmcd() {
        return hmcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.HMCD
     *
     * @param hmcd the value for BIZ_DRV_INFO.HMCD
     *
     * @mbggenerated
     */
    public void setHmcd(String hmcd) {
        this.hmcd = hmcd == null ? null : hmcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.XM
     *
     * @return the value of BIZ_DRV_INFO.XM
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.XM
     *
     * @param xm the value for BIZ_DRV_INFO.XM
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.XB
     *
     * @return the value of BIZ_DRV_INFO.XB
     *
     * @mbggenerated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.XB
     *
     * @param xb the value for BIZ_DRV_INFO.XB
     *
     * @mbggenerated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.CSRQ
     *
     * @return the value of BIZ_DRV_INFO.CSRQ
     *
     * @mbggenerated
     */
    public Date getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.CSRQ
     *
     * @param csrq the value for BIZ_DRV_INFO.CSRQ
     *
     * @mbggenerated
     */
    public void setCsrq(Date csrq) {
        this.csrq = csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.GJ
     *
     * @return the value of BIZ_DRV_INFO.GJ
     *
     * @mbggenerated
     */
    public String getGj() {
        return gj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.GJ
     *
     * @param gj the value for BIZ_DRV_INFO.GJ
     *
     * @mbggenerated
     */
    public void setGj(String gj) {
        this.gj = gj == null ? null : gj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.DJZSXZQH
     *
     * @return the value of BIZ_DRV_INFO.DJZSXZQH
     *
     * @mbggenerated
     */
    public String getDjzsxzqh() {
        return djzsxzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.DJZSXZQH
     *
     * @param djzsxzqh the value for BIZ_DRV_INFO.DJZSXZQH
     *
     * @mbggenerated
     */
    public void setDjzsxzqh(String djzsxzqh) {
        this.djzsxzqh = djzsxzqh == null ? null : djzsxzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.DJZSXXDZ
     *
     * @return the value of BIZ_DRV_INFO.DJZSXXDZ
     *
     * @mbggenerated
     */
    public String getDjzsxxdz() {
        return djzsxxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.DJZSXXDZ
     *
     * @param djzsxxdz the value for BIZ_DRV_INFO.DJZSXXDZ
     *
     * @mbggenerated
     */
    public void setDjzsxxdz(String djzsxxdz) {
        this.djzsxxdz = djzsxxdz == null ? null : djzsxxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.LXZSXZQH
     *
     * @return the value of BIZ_DRV_INFO.LXZSXZQH
     *
     * @mbggenerated
     */
    public String getLxzsxzqh() {
        return lxzsxzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.LXZSXZQH
     *
     * @param lxzsxzqh the value for BIZ_DRV_INFO.LXZSXZQH
     *
     * @mbggenerated
     */
    public void setLxzsxzqh(String lxzsxzqh) {
        this.lxzsxzqh = lxzsxzqh == null ? null : lxzsxzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.LXZSXXDZ
     *
     * @return the value of BIZ_DRV_INFO.LXZSXXDZ
     *
     * @mbggenerated
     */
    public String getLxzsxxdz() {
        return lxzsxxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.LXZSXXDZ
     *
     * @param lxzsxxdz the value for BIZ_DRV_INFO.LXZSXXDZ
     *
     * @mbggenerated
     */
    public void setLxzsxxdz(String lxzsxxdz) {
        this.lxzsxxdz = lxzsxxdz == null ? null : lxzsxxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.LXZSYZBM
     *
     * @return the value of BIZ_DRV_INFO.LXZSYZBM
     *
     * @mbggenerated
     */
    public String getLxzsyzbm() {
        return lxzsyzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.LXZSYZBM
     *
     * @param lxzsyzbm the value for BIZ_DRV_INFO.LXZSYZBM
     *
     * @mbggenerated
     */
    public void setLxzsyzbm(String lxzsyzbm) {
        this.lxzsyzbm = lxzsyzbm == null ? null : lxzsyzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.LXDH
     *
     * @return the value of BIZ_DRV_INFO.LXDH
     *
     * @mbggenerated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.LXDH
     *
     * @param lxdh the value for BIZ_DRV_INFO.LXDH
     *
     * @mbggenerated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.SJHM
     *
     * @return the value of BIZ_DRV_INFO.SJHM
     *
     * @mbggenerated
     */
    public String getSjhm() {
        return sjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.SJHM
     *
     * @param sjhm the value for BIZ_DRV_INFO.SJHM
     *
     * @mbggenerated
     */
    public void setSjhm(String sjhm) {
        this.sjhm = sjhm == null ? null : sjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.DZYX
     *
     * @return the value of BIZ_DRV_INFO.DZYX
     *
     * @mbggenerated
     */
    public String getDzyx() {
        return dzyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.DZYX
     *
     * @param dzyx the value for BIZ_DRV_INFO.DZYX
     *
     * @mbggenerated
     */
    public void setDzyx(String dzyx) {
        this.dzyx = dzyx == null ? null : dzyx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.DABH
     *
     * @return the value of BIZ_DRV_INFO.DABH
     *
     * @mbggenerated
     */
    public String getDabh() {
        return dabh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.DABH
     *
     * @param dabh the value for BIZ_DRV_INFO.DABH
     *
     * @mbggenerated
     */
    public void setDabh(String dabh) {
        this.dabh = dabh == null ? null : dabh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.ZJCX
     *
     * @return the value of BIZ_DRV_INFO.ZJCX
     *
     * @mbggenerated
     */
    public String getZjcx() {
        return zjcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.ZJCX
     *
     * @param zjcx the value for BIZ_DRV_INFO.ZJCX
     *
     * @mbggenerated
     */
    public void setZjcx(String zjcx) {
        this.zjcx = zjcx == null ? null : zjcx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.LJJF
     *
     * @return the value of BIZ_DRV_INFO.LJJF
     *
     * @mbggenerated
     */
    public Short getLjjf() {
        return ljjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.LJJF
     *
     * @param ljjf the value for BIZ_DRV_INFO.LJJF
     *
     * @mbggenerated
     */
    public void setLjjf(Short ljjf) {
        this.ljjf = ljjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.ZT
     *
     * @return the value of BIZ_DRV_INFO.ZT
     *
     * @mbggenerated
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.ZT
     *
     * @param zt the value for BIZ_DRV_INFO.ZT
     *
     * @mbggenerated
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.CCLZRQ
     *
     * @return the value of BIZ_DRV_INFO.CCLZRQ
     *
     * @mbggenerated
     */
    public Date getCclzrq() {
        return cclzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.CCLZRQ
     *
     * @param cclzrq the value for BIZ_DRV_INFO.CCLZRQ
     *
     * @mbggenerated
     */
    public void setCclzrq(Date cclzrq) {
        this.cclzrq = cclzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.JZQX
     *
     * @return the value of BIZ_DRV_INFO.JZQX
     *
     * @mbggenerated
     */
    public Date getJzqx() {
        return jzqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.JZQX
     *
     * @param jzqx the value for BIZ_DRV_INFO.JZQX
     *
     * @mbggenerated
     */
    public void setJzqx(Date jzqx) {
        this.jzqx = jzqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.SYRQ
     *
     * @return the value of BIZ_DRV_INFO.SYRQ
     *
     * @mbggenerated
     */
    public Date getSyrq() {
        return syrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.SYRQ
     *
     * @param syrq the value for BIZ_DRV_INFO.SYRQ
     *
     * @mbggenerated
     */
    public void setSyrq(Date syrq) {
        this.syrq = syrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.YXQS
     *
     * @return the value of BIZ_DRV_INFO.YXQS
     *
     * @mbggenerated
     */
    public Date getYxqs() {
        return yxqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.YXQS
     *
     * @param yxqs the value for BIZ_DRV_INFO.YXQS
     *
     * @mbggenerated
     */
    public void setYxqs(Date yxqs) {
        this.yxqs = yxqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.YXQZ
     *
     * @return the value of BIZ_DRV_INFO.YXQZ
     *
     * @mbggenerated
     */
    public Date getYxqz() {
        return yxqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.YXQZ
     *
     * @param yxqz the value for BIZ_DRV_INFO.YXQZ
     *
     * @mbggenerated
     */
    public void setYxqz(Date yxqz) {
        this.yxqz = yxqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.XZQH
     *
     * @return the value of BIZ_DRV_INFO.XZQH
     *
     * @mbggenerated
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.XZQH
     *
     * @param xzqh the value for BIZ_DRV_INFO.XZQH
     *
     * @mbggenerated
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh == null ? null : xzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.ZZZM
     *
     * @return the value of BIZ_DRV_INFO.ZZZM
     *
     * @mbggenerated
     */
    public String getZzzm() {
        return zzzm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.ZZZM
     *
     * @param zzzm the value for BIZ_DRV_INFO.ZZZM
     *
     * @mbggenerated
     */
    public void setZzzm(String zzzm) {
        this.zzzm = zzzm == null ? null : zzzm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.GXSJ
     *
     * @return the value of BIZ_DRV_INFO.GXSJ
     *
     * @mbggenerated
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.GXSJ
     *
     * @param gxsj the value for BIZ_DRV_INFO.GXSJ
     *
     * @mbggenerated
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.ZXBH
     *
     * @return the value of BIZ_DRV_INFO.ZXBH
     *
     * @mbggenerated
     */
    public String getZxbh() {
        return zxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.ZXBH
     *
     * @param zxbh the value for BIZ_DRV_INFO.ZXBH
     *
     * @mbggenerated
     */
    public void setZxbh(String zxbh) {
        this.zxbh = zxbh == null ? null : zxbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.FZJG
     *
     * @return the value of BIZ_DRV_INFO.FZJG
     *
     * @mbggenerated
     */
    public String getFzjg() {
        return fzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.FZJG
     *
     * @param fzjg the value for BIZ_DRV_INFO.FZJG
     *
     * @mbggenerated
     */
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg == null ? null : fzjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.ZHQFRQ
     *
     * @return the value of BIZ_DRV_INFO.ZHQFRQ
     *
     * @mbggenerated
     */
    public Date getZhqfrq() {
        return zhqfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.ZHQFRQ
     *
     * @param zhqfrq the value for BIZ_DRV_INFO.ZHQFRQ
     *
     * @mbggenerated
     */
    public void setZhqfrq(Date zhqfrq) {
        this.zhqfrq = zhqfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.MFQFRQ
     *
     * @return the value of BIZ_DRV_INFO.MFQFRQ
     *
     * @mbggenerated
     */
    public Date getMfqfrq() {
        return mfqfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.MFQFRQ
     *
     * @param mfqfrq the value for BIZ_DRV_INFO.MFQFRQ
     *
     * @mbggenerated
     */
    public void setMfqfrq(Date mfqfrq) {
        this.mfqfrq = mfqfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.XYQFRQ
     *
     * @return the value of BIZ_DRV_INFO.XYQFRQ
     *
     * @mbggenerated
     */
    public Date getXyqfrq() {
        return xyqfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.XYQFRQ
     *
     * @param xyqfrq the value for BIZ_DRV_INFO.XYQFRQ
     *
     * @mbggenerated
     */
    public void setXyqfrq(Date xyqfrq) {
        this.xyqfrq = xyqfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.SFCF
     *
     * @return the value of BIZ_DRV_INFO.SFCF
     *
     * @mbggenerated
     */
    public String getSfcf() {
        return sfcf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.SFCF
     *
     * @param sfcf the value for BIZ_DRV_INFO.SFCF
     *
     * @mbggenerated
     */
    public void setSfcf(String sfcf) {
        this.sfcf = sfcf == null ? null : sfcf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.YQWSY
     *
     * @return the value of BIZ_DRV_INFO.YQWSY
     *
     * @mbggenerated
     */
    public String getYqwsy() {
        return yqwsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.YQWSY
     *
     * @param yqwsy the value for BIZ_DRV_INFO.YQWSY
     *
     * @mbggenerated
     */
    public void setYqwsy(String yqwsy) {
        this.yqwsy = yqwsy == null ? null : yqwsy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.YQWHZ
     *
     * @return the value of BIZ_DRV_INFO.YQWHZ
     *
     * @mbggenerated
     */
    public String getYqwhz() {
        return yqwhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.YQWHZ
     *
     * @param yqwhz the value for BIZ_DRV_INFO.YQWHZ
     *
     * @mbggenerated
     */
    public void setYqwhz(String yqwhz) {
        this.yqwhz = yqwhz == null ? null : yqwhz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_DRV_INFO.XRSJ
     *
     * @return the value of BIZ_DRV_INFO.XRSJ
     *
     * @mbggenerated
     */
    public Date getXrsj() {
        return xrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_DRV_INFO.XRSJ
     *
     * @param xrsj the value for BIZ_DRV_INFO.XRSJ
     *
     * @mbggenerated
     */
    public void setXrsj(Date xrsj) {
        this.xrsj = xrsj;
    }
}