package com.scxd.beans.pojo.test;

import com.scxd.common.JaxbDateAdapter;
import com.scxd.common.JaxbStringAdapter;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.Date;

public class BizVehInfoBean {
    private String id;

    private String zt;

    private Date yxqz;

    private String fzjg;

    private String hphm;

    private String hpzl;

    private String clpp1;

    private String sfdqc;

    private String csys;

    private String zsxzqh;

    private String jdcbgyy;

    private Date hpqyrq;

    private Date ccdjrq;

    private String syr;

    private String syxz;

    private String clsbdh;

    private String gcjk;

    private Date bxzzrq;

    private String hgzbh;

    private String fdjh;

    private String xszbh;

    private Short pl;

    private String gl;

    private String dybj;

    private Short cwkc;

    private Short cwkk;

    private Short cwkg;

    private String zdcllx;

    private String cllx;

    private Short wfcs;

    private String sfwfwcl;

    private String sfyqwjy;

    private String sfyqwbf;

    private String lxdh;

    private String zsxxdz;

    private Date xrsj;

    private Date qzbfqz;

    private String clxh;

    private Short zbzl;

    private String fdjxh;

    private Date ccrq;

    private Short hlj;

    private Short zzl;

    private String rlzl;

    private Short hdzk;

    private Short qlj;

    private Short zj;

    private Short hdzzl;

    private Short zs;

    private String dabh;

    private String qpzk;

    private String hbdbqk;

    private String sjhm;

    private String hxnbkd;

    private String hxnbgd;

    private String hxnbcd;

    private String zzg;

    private String clpp2;

    private String jyhgbzbh;

    private String zxxs;

    private String hpzk;

    private Date djrq;

    private String sfzmhm;

    private String gbthps;

    private String zqyzl;

    private String zzxxdz;

    private String sfzmmc;

    private String ltgg;

    private String lts;

    private String glbm;

    private String zzcmc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.ID
     *
     * @return the value of BIZ_VEH_INFO.ID
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.ID
     *
     * @param id the value for BIZ_VEH_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.ZT
     *
     * @return the value of BIZ_VEH_INFO.ZT
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.ZT
     *
     * @param zt the value for BIZ_VEH_INFO.ZT
     *
     * @mbggenerated
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.YXQZ
     *
     * @return the value of BIZ_VEH_INFO.YXQZ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getYxqz() {
        return yxqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.YXQZ
     *
     * @param yxqz the value for BIZ_VEH_INFO.YXQZ
     *
     * @mbggenerated
     */
    public void setYxqz(Date yxqz) {
        this.yxqz = yxqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.FZJG
     *
     * @return the value of BIZ_VEH_INFO.FZJG
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getFzjg() {
        return fzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.FZJG
     *
     * @param fzjg the value for BIZ_VEH_INFO.FZJG
     *
     * @mbggenerated
     */
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg == null ? null : fzjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.HPHM
     *
     * @return the value of BIZ_VEH_INFO.HPHM
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getHphm() {
        return hphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.HPHM
     *
     * @param hphm the value for BIZ_VEH_INFO.HPHM
     *
     * @mbggenerated
     */
    public void setHphm(String hphm) {
        this.hphm = hphm == null ? null : hphm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.HPZL
     *
     * @return the value of BIZ_VEH_INFO.HPZL
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getHpzl() {
        return hpzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.HPZL
     *
     * @param hpzl the value for BIZ_VEH_INFO.HPZL
     *
     * @mbggenerated
     */
    public void setHpzl(String hpzl) {
        this.hpzl = hpzl == null ? null : hpzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.CLPP1
     *
     * @return the value of BIZ_VEH_INFO.CLPP1
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getClpp1() {
        return clpp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.CLPP1
     *
     * @param clpp1 the value for BIZ_VEH_INFO.CLPP1
     *
     * @mbggenerated
     */
    public void setClpp1(String clpp1) {
        this.clpp1 = clpp1 == null ? null : clpp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.SFDQC
     *
     * @return the value of BIZ_VEH_INFO.SFDQC
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getSfdqc() {
        return sfdqc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.SFDQC
     *
     * @param sfdqc the value for BIZ_VEH_INFO.SFDQC
     *
     * @mbggenerated
     */
    public void setSfdqc(String sfdqc) {
        this.sfdqc = sfdqc == null ? null : sfdqc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.CSYS
     *
     * @return the value of BIZ_VEH_INFO.CSYS
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getCsys() {
        return csys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.CSYS
     *
     * @param csys the value for BIZ_VEH_INFO.CSYS
     *
     * @mbggenerated
     */
    public void setCsys(String csys) {
        this.csys = csys == null ? null : csys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.ZSXZQH
     *
     * @return the value of BIZ_VEH_INFO.ZSXZQH
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getZsxzqh() {
        return zsxzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.ZSXZQH
     *
     * @param zsxzqh the value for BIZ_VEH_INFO.ZSXZQH
     *
     * @mbggenerated
     */
    public void setZsxzqh(String zsxzqh) {
        this.zsxzqh = zsxzqh == null ? null : zsxzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.JDCBGYY
     *
     * @return the value of BIZ_VEH_INFO.JDCBGYY
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getJdcbgyy() {
        return jdcbgyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.JDCBGYY
     *
     * @param jdcbgyy the value for BIZ_VEH_INFO.JDCBGYY
     *
     * @mbggenerated
     */
    public void setJdcbgyy(String jdcbgyy) {
        this.jdcbgyy = jdcbgyy == null ? null : jdcbgyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.HPQYRQ
     *
     * @return the value of BIZ_VEH_INFO.HPQYRQ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getHpqyrq() {
        return hpqyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.HPQYRQ
     *
     * @param hpqyrq the value for BIZ_VEH_INFO.HPQYRQ
     *
     * @mbggenerated
     */
    public void setHpqyrq(Date hpqyrq) {
        this.hpqyrq = hpqyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.CCDJRQ
     *
     * @return the value of BIZ_VEH_INFO.CCDJRQ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getCcdjrq() {
        return ccdjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.CCDJRQ
     *
     * @param ccdjrq the value for BIZ_VEH_INFO.CCDJRQ
     *
     * @mbggenerated
     */
    public void setCcdjrq(Date ccdjrq) {
        this.ccdjrq = ccdjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.SYR
     *
     * @return the value of BIZ_VEH_INFO.SYR
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getSyr() {
        return syr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.SYR
     *
     * @param syr the value for BIZ_VEH_INFO.SYR
     *
     * @mbggenerated
     */
    public void setSyr(String syr) {
        this.syr = syr == null ? null : syr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.SYXZ
     *
     * @return the value of BIZ_VEH_INFO.SYXZ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getSyxz() {
        return syxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.SYXZ
     *
     * @param syxz the value for BIZ_VEH_INFO.SYXZ
     *
     * @mbggenerated
     */
    public void setSyxz(String syxz) {
        this.syxz = syxz == null ? null : syxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.CLSBDH
     *
     * @return the value of BIZ_VEH_INFO.CLSBDH
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getClsbdh() {
        return clsbdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.CLSBDH
     *
     * @param clsbdh the value for BIZ_VEH_INFO.CLSBDH
     *
     * @mbggenerated
     */
    public void setClsbdh(String clsbdh) {
        this.clsbdh = clsbdh == null ? null : clsbdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.GCJK
     *
     * @return the value of BIZ_VEH_INFO.GCJK
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getGcjk() {
        return gcjk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.GCJK
     *
     * @param gcjk the value for BIZ_VEH_INFO.GCJK
     *
     * @mbggenerated
     */
    public void setGcjk(String gcjk) {
        this.gcjk = gcjk == null ? null : gcjk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.BXZZRQ
     *
     * @return the value of BIZ_VEH_INFO.BXZZRQ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getBxzzrq() {
        return bxzzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.BXZZRQ
     *
     * @param bxzzrq the value for BIZ_VEH_INFO.BXZZRQ
     *
     * @mbggenerated
     */
    public void setBxzzrq(Date bxzzrq) {
        this.bxzzrq = bxzzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.HGZBH
     *
     * @return the value of BIZ_VEH_INFO.HGZBH
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getHgzbh() {
        return hgzbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.HGZBH
     *
     * @param hgzbh the value for BIZ_VEH_INFO.HGZBH
     *
     * @mbggenerated
     */
    public void setHgzbh(String hgzbh) {
        this.hgzbh = hgzbh == null ? null : hgzbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.FDJH
     *
     * @return the value of BIZ_VEH_INFO.FDJH
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getFdjh() {
        return fdjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.FDJH
     *
     * @param fdjh the value for BIZ_VEH_INFO.FDJH
     *
     * @mbggenerated
     */
    public void setFdjh(String fdjh) {
        this.fdjh = fdjh == null ? null : fdjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.XSZBH
     *
     * @return the value of BIZ_VEH_INFO.XSZBH
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getXszbh() {
        return xszbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.XSZBH
     *
     * @param xszbh the value for BIZ_VEH_INFO.XSZBH
     *
     * @mbggenerated
     */
    public void setXszbh(String xszbh) {
        this.xszbh = xszbh == null ? null : xszbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.PL
     *
     * @return the value of BIZ_VEH_INFO.PL
     *
     * @mbggenerated
     */
    public Short getPl() {
        return pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.PL
     *
     * @param pl the value for BIZ_VEH_INFO.PL
     *
     * @mbggenerated
     */
    public void setPl(Short pl) {
        this.pl = pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.GL
     *
     * @return the value of BIZ_VEH_INFO.GL
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getGl() {
        return gl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.GL
     *
     * @param gl the value for BIZ_VEH_INFO.GL
     *
     * @mbggenerated
     */
    public void setGl(String gl) {
        this.gl = gl == null ? null : gl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.DYBJ
     *
     * @return the value of BIZ_VEH_INFO.DYBJ
     *
     * @mbggenerated
     */
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getDybj() {
        return dybj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.DYBJ
     *
     * @param dybj the value for BIZ_VEH_INFO.DYBJ
     *
     * @mbggenerated
     */
    public void setDybj(String dybj) {
        this.dybj = dybj == null ? null : dybj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_VEH_INFO.CWKC
     *
     * @return the value of BIZ_VEH_INFO.CWKC
     *
     * @mbggenerated
     */
    public Short getCwkc() {
        return cwkc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_VEH_INFO.CWKC
     *
     * @param cwkc the value for BIZ_VEH_INFO.CWKC
     *
     * @mbggenerated
     */
    public void setCwkc(Short cwkc) {
        this.cwkc = cwkc;
    }

    public Short getCwkk() {
        return cwkk;
    }

    public void setCwkk(Short cwkk) {
        this.cwkk = cwkk;
    }

    public Short getCwkg() {
        return cwkg;
    }

    public void setCwkg(Short cwkg) {
        this.cwkg = cwkg;
    }

    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getZdcllx() {
        return zdcllx;
    }

    public void setZdcllx(String zdcllx) {
        this.zdcllx = zdcllx == null ? null : zdcllx.trim();
    }

    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getCllx() {
        return cllx;
    }

    public void setCllx(String cllx) {
        this.cllx = cllx == null ? null : cllx.trim();
    }

    public Short getWfcs() {
        return wfcs;
    }

    public void setWfcs(Short wfcs) {
        this.wfcs = wfcs;
    }

    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getSfwfwcl() {
        return sfwfwcl;
    }

    public void setSfwfwcl(String sfwfwcl) {
        this.sfwfwcl = sfwfwcl == null ? null : sfwfwcl.trim();
    }

    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getSfyqwjy() {
        return sfyqwjy;
    }

    public void setSfyqwjy(String sfyqwjy) {
        this.sfyqwjy = sfyqwjy == null ? null : sfyqwjy.trim();
    }

    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getSfyqwbf() {
        return sfyqwbf;
    }

    public void setSfyqwbf(String sfyqwbf) {
        this.sfyqwbf = sfyqwbf == null ? null : sfyqwbf.trim();
    }

    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getLxdh() {
        return lxdh;
    }

    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getZsxxdz() {
        return zsxxdz;
    }

    public void setZsxxdz(String zsxxdz) {
        this.zsxxdz = zsxxdz == null ? null : zsxxdz.trim();
    }

    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getXrsj() {
        return xrsj;
    }

    public void setXrsj(Date xrsj) {
        this.xrsj = xrsj;
    }

    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getQzbfqz() {
        return qzbfqz;
    }

    public void setQzbfqz(Date qzbfqz) {
        this.qzbfqz = qzbfqz;
    }

    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getClxh() {
        return clxh;
    }

    public void setClxh(String clxh) {
        this.clxh = clxh == null ? null : clxh.trim();
    }

    public Short getZbzl() {
        return zbzl;
    }

    public void setZbzl(Short zbzl) {
        this.zbzl = zbzl;
    }

    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getFdjxh() {
        return fdjxh;
    }

    public void setFdjxh(String fdjxh) {
        this.fdjxh = fdjxh == null ? null : fdjxh.trim();
    }

    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getCcrq() {
        return ccrq;
    }

    public void setCcrq(Date ccrq) {
        this.ccrq = ccrq;
    }

    public Short getHlj() {
        return hlj;
    }

    public void setHlj(Short hlj) {
        this.hlj = hlj;
    }

    public Short getZzl() {
        return zzl;
    }

    public void setZzl(Short zzl) {
        this.zzl = zzl;
    }

    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getRlzl() {
        return rlzl;
    }

    public void setRlzl(String rlzl) {
        this.rlzl = rlzl == null ? null : rlzl.trim();
    }

    public Short getHdzk() {
        return hdzk;
    }

    public void setHdzk(Short hdzk) {
        this.hdzk = hdzk;
    }

    public Short getQlj() {
        return qlj;
    }

    public void setQlj(Short qlj) {
        this.qlj = qlj;
    }

    public Short getZj() {
        return zj;
    }

    public void setZj(Short zj) {
        this.zj = zj;
    }

    public Short getHdzzl() {
        return hdzzl;
    }

    public void setHdzzl(Short hdzzl) {
        this.hdzzl = hdzzl;
    }

    public Short getZs() {
        return zs;
    }

    public void setZs(Short zs) {
        this.zs = zs;
    }
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getDabh() {
        return dabh;
    }

    public void setDabh(String dabh) {
        this.dabh = dabh;
    }
    @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getQpzk() {
        return qpzk;
    }

    public void setQpzk(String qpzk) {
        this.qpzk = qpzk;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getHbdbqk() {
        return hbdbqk;
    }

    public void setHbdbqk(String hbdbqk) {
        this.hbdbqk = hbdbqk;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getSjhm() {
        return sjhm;
    }

    public void setSjhm(String sjhm) {
        this.sjhm = sjhm;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getHxnbkd() {
        return hxnbkd;
    }

    public void setHxnbkd(String hxnbkd) {
        this.hxnbkd = hxnbkd;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getHxnbgd() {
        return hxnbgd;
    }

    public void setHxnbgd(String hxnbgd) {
        this.hxnbgd = hxnbgd;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getHxnbcd() {
        return hxnbcd;
    }

    public void setHxnbcd(String hxnbcd) {
        this.hxnbcd = hxnbcd;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getZzg() {
        return zzg;
    }

    public void setZzg(String zzg) {
        this.zzg = zzg;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getClpp2() {
        return clpp2;
    }

    public void setClpp2(String clpp2) {
        this.clpp2 = clpp2;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getJyhgbzbh() {
        return jyhgbzbh;
    }

    public void setJyhgbzbh(String jyhgbzbh) {
        this.jyhgbzbh = jyhgbzbh;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getZxxs() {
        return zxxs;
    }

    public void setZxxs(String zxxs) {
        this.zxxs = zxxs;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getHpzk() {
        return hpzk;
    }

    public void setHpzk(String hpzk) {
        this.hpzk = hpzk;
    }

   @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    public Date getDjrq() {
        return djrq;
    }

    public void setDjrq(Date djrq) {
        this.djrq = djrq;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getSfzmhm() {
        return sfzmhm;
    }

    public void setSfzmhm(String sfzmhm) {
        this.sfzmhm = sfzmhm;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getGbthps() {
        return gbthps;
    }

    public void setGbthps(String gbthps) {
        this.gbthps = gbthps;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getZqyzl() {
        return zqyzl;
    }

    public void setZqyzl(String zqyzl) {
        this.zqyzl = zqyzl;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getZzxxdz() {
        return zzxxdz;
    }

    public void setZzxxdz(String zzxxdz) {
        this.zzxxdz = zzxxdz;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getSfzmmc() {
        return sfzmmc;
    }

    public void setSfzmmc(String sfzmmc) {
        this.sfzmmc = sfzmmc;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getLtgg() {
        return ltgg;
    }

    public void setLtgg(String ltgg) {
        this.ltgg = ltgg;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getLts() {
        return lts;
    }

    public void setLts(String lts) {
        this.lts = lts;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getGlbm() {
        return glbm;
    }

    public void setGlbm(String glbm) {
        this.glbm = glbm;
    }

     @XmlJavaTypeAdapter(JaxbStringAdapter.class)
    public String getZzcmc() {
        return zzcmc;
    }

    public void setZzcmc(String zzcmc) {
        this.zzcmc = zzcmc;
    }
}