package com.scxd.dao.mapper;

import com.scxd.beans.biz.Q12Return;
import com.scxd.beans.pdaBeans.request.PdaFeedBackRequest;
import com.scxd.beans.pdaBeans.response.Q07ReturnBean;
import com.scxd.beans.pojo.BizAlarmInfo;
import com.scxd.beans.pojo.BizRmConfig;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface BizAlarmInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ALARM_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String yjxh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ALARM_INFO
     *
     * @mbggenerated
     */
    int insert(BizAlarmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ALARM_INFO
     *
     * @mbggenerated
     */
    int insertSelective(BizAlarmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ALARM_INFO
     *
     * @mbggenerated
     */
    BizAlarmInfo selectByPrimaryKey(String yjxh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ALARM_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizAlarmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ALARM_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizAlarmInfo record);


    List<Q12Return> getYJlist(Map<String, Object> map);

    Q07ReturnBean getYJDetails(String yjxh);

    int  updateQSMessage(Map<String, Object> map);

    int updateFeedBackMessage(PdaFeedBackRequest feedBackRequest);

    PdaFeedBackRequest getYJFeedBackDetails(@Param("yjxh") String yjxh,@Param("sjbmbh") String sjbmbh);

    int getYJlistTotal(Map<String, Object> map);
}