package com.scxd.dao.mapper;

import com.scxd.beans.pdaBeans.response.CodeValueCommon;
import com.scxd.beans.pdaBeans.response.PdaKKResponse;
import com.scxd.beans.pdaBeans.response.Q26ReturnBean;
import com.scxd.beans.pdaBeans.response.Q27ReturnBean;
import com.scxd.beans.pojo.BizRoadBlocks;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface BizRoadBlocksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ROAD_BLOCKS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ROAD_BLOCKS
     *
     * @mbggenerated
     */
    int insert(BizRoadBlocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ROAD_BLOCKS
     *
     * @mbggenerated
     */
    int insertSelective(BizRoadBlocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ROAD_BLOCKS
     *
     * @mbggenerated
     */
    BizRoadBlocks selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ROAD_BLOCKS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizRoadBlocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ROAD_BLOCKS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizRoadBlocks record);

  //  List<CodeValueCommon> getKKMessageByBmbh(Map<String, Object> bmbh);

    //删除来源ly = 1的信息
    int deleteBizRoadBlockByLy(@Param("bmbh")String bmbh);

    //批量插入
    int insertRoadBlocks(@Param("roadBlocksList") List<BizRoadBlocks> listmap);


    List<Q26ReturnBean> getRoadItem(Map<String, String> map);


    List<Q27ReturnBean> getRoadSegItem(Map<String, String> map);

    List<CodeValueCommon> getKKMessageByBmbh(@Param("type")int type,@Param("bmbh") String ssbmbh,@Param("user") String user);
}