package com.scxd.dao.mapper;

import com.scxd.beans.pdaBeans.response.CodeYjBean;
import com.scxd.beans.pojo.BizRmConfig;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface BizRmConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG
     *
     * @mbggenerated
     */
    int insert(BizRmConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG
     *
     * @mbggenerated
     */
    int insertSelective(BizRmConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG
     *
     * @mbggenerated
     */
    BizRmConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizRmConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizRmConfig record);

    BizRmConfig getLastKKMessage(Map<String, Object> map);

    List<CodeYjBean> getYJMessage(Map<String, Object> map);


    String selectIDByUser(String user);

    int updateTSZTByUser(String user,String tszt);

    int updateBKDateByUser(String user, Date date);
}