package com.scxd.dao.mapper;

import com.scxd.beans.pojo.BizRmConfigDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BizRmConfigDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG_DETAIL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG_DETAIL
     *
     * @mbggenerated
     */
    int insert(BizRmConfigDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG_DETAIL
     *
     * @mbggenerated
     */
    int insertSelective(BizRmConfigDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG_DETAIL
     *
     * @mbggenerated
     */
    BizRmConfigDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG_DETAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizRmConfigDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_RM_CONFIG_DETAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizRmConfigDetail record);

    void deleteByRMKey(String pID);

    int insertSelectiveList(@Param("configDetails") List<BizRmConfigDetail> configDetails);
}