package com.scxd.dao.mapper;

import com.scxd.beans.pdaBeans.response.Q18ReturnBean;
import com.scxd.beans.pdaBeans.response.Q21ReturnBean;
import com.scxd.beans.pojo.BizVioForce;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface BizVioForceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_VIO_FORCE
     *
     * @mbggenerated
     */
    int insert(BizVioForce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_VIO_FORCE
     *
     * @mbggenerated
     */
    int insertSelective(BizVioForce record);

    List<Q18ReturnBean> getForceDocument(Map<String, Object> map);

    Q21ReturnBean getForceDocumentDetail(@Param("pzbh") String pzbh);

    int updatePrint(String xh);
    String  getForceDocumentBH();

    void deleteVioForceById(String id);

    int updateWsjywByPzbh(@Param("wsjyw")String wsjyw,@Param("pzbh")String pzbh);

    String getDocumentNumberByBmbhAndUser(@Param("bmbh")String bmbh,@Param("wslb") String wslb, @Param("user")String user);

    int getForceDocTotal(Map<String, Object> map);
}