package com.scxd.dao.mapper;

import com.scxd.beans.pdaBeans.response.Q17ReturnBean;
import com.scxd.beans.pdaBeans.response.Q20ReturnBean;
import com.scxd.beans.pojo.BizVioViolation;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface BizVioViolationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_VIO_VIOLATION
     *
     * @mbggenerated
     */
    int insert(BizVioViolation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_VIO_VIOLATION
     *
     * @mbggenerated
     */
    int insertSelective(BizVioViolation record);

    List<Q17ReturnBean> getSimDocument(Map<String, Object> map);

    int getSimDocTotal(Map<String, Object> map);

    Q20ReturnBean getSimDocumentDetail(@Param("jdsbh") String jdsbh);

    void deleteByBizVioValation(String key);

    int updatePrint(String xh);

    String getSimDocumentBH();

    int updateWsjywByJdsbh(@Param("jdsbh")String jdsbh,@Param("wsjyw") String wsjyw);
}