package com.scxd.dao.mapper;

import com.scxd.beans.pojo.PdaCashBean;

public interface PdaCashBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int insert(PdaCashBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int insertSelective(PdaCashBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    PdaCashBean selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PdaCashBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(PdaCashBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PdaCashBean record);
}