package com.scxd.dao.mapper;

import com.scxd.beans.management.Dept;
import com.scxd.beans.pojo.SysDepartment;

import java.util.HashMap;
import java.util.List;


public interface SysDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPARTMENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPARTMENT
     *
     * @mbggenerated
     */
    int insert(SysDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPARTMENT
     *
     * @mbggenerated
     */
    int insertSelective(SysDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPARTMENT
     *
     * @mbggenerated
     */
    SysDepartment selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPARTMENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_DEPARTMENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysDepartment record);

    List<String> getZDBMBHs();


}