package com.scxd.dao.mapper;

import com.scxd.beans.pojo.SysIfLog;
import com.scxd.beans.pojo.SysIfLogWithBLOBs;

public interface SysIfLogMapper {
    int insert(SysIfLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_IF_LOG
     *
     * @mbggenerated
     */
    int insertSelective(SysIfLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_IF_LOG
     *
     * @mbggenerated
     */
    SysIfLogWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_IF_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysIfLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_IF_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SysIfLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_IF_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysIfLog record);
}