package com.scxd.dao.mapper;

import com.scxd.beans.common.MenuBean;
import com.scxd.beans.pojo.SysMenu;
import com.scxd.beans.pojo.SysMenuDetail;

import java.util.List;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    int insert(MenuBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    int insertSelective(SysMenu record);

    List<SysMenu> selectByUserName(String userName);
    List<SysMenu> selectAdminMenu(String userName);
    public List<SysMenu> getMenusList();

    List<SysMenu> selectAllMenu();

}