package com.scxd.dao.mapper;


import com.scxd.beans.pojo.SysMenuRole;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysMenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int insert(SysMenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_role
     *
     * @mbggenerated
     */
    int insertSelective(SysMenuRole record);

    int  deleteByRoleId(int roleId);


    int insertArray(@Param("sysMenuRoles")List<SysMenuRole> sysMenuRoles);
}