package com.scxd.dao.mapper;

import com.scxd.beans.management.PdaBean;
import com.scxd.beans.pojo.SysPdaInfo;
import com.scxd.beans.pojo.SysPdaVersion;

import java.util.HashMap;
import java.util.List;

public interface SysPdaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_INFO
     *
     * @mbggenerated
     */
    int insert(SysPdaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_INFO
     *
     * @mbggenerated
     */
    int insertSelective(SysPdaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_INFO
     *
     * @mbggenerated
     */
    SysPdaInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysPdaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysPdaInfo record);


   List<PdaBean> getPdaMessage(HashMap map);
    List<PdaBean>  getPdaMessageCount(HashMap map);
    List<SysPdaInfo> getPdaMessageByWym(String wym);

}