package com.scxd.dao.mapper;

import com.scxd.beans.pojo.SysPdaLog;
import com.scxd.beans.pojo.SysPdaLogWithBLOBs;

public interface SysPdaLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int insert(SysPdaLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int insertSelective(SysPdaLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    SysPdaLogWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysPdaLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SysPdaLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PDA_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysPdaLog record);
}