package com.scxd.dao.mapper;


import com.scxd.beans.common.User;
import com.scxd.beans.management.RoleBean;
import com.scxd.beans.pdaBeans.request.PdaUser;
import com.scxd.beans.pdaBeans.response.PdaResponse;
import com.scxd.beans.pojo.SysUser;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.Map;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insertSelective(SysUser record);

    SysUser selectByUserName(String userName);

    User selectUserByUserName(String userName);

    PdaResponse selectPdaUser(PdaUser pdaUser);

    Map<String,String> selectBmbhANDRealName(String user);

    //通过部门编号和用户名来查询用户是否存在
    int selectCheckUser(String user,String bmbh);

    int updatePassword(Map<String, Object> map);

    String selectPwd(String user,String bmbh);

    Map selectUserInfo(String loginname,String bmbh);

    User getUseById(@Param("id") String id);

    int addUserByUser(SysUser user);

    int addUserByRole(RoleBean roleBean);

    int updateUserByRole(RoleBean roleBean);

    int getUserBySfzhm(@Param("sfzmhm")String sfzmhm);
    int getUserBySfzhmUpdate(SysUser user);

    int getUserByLoginname(@Param("loginname")String loginname);

    int getUserByYgbh(@Param("ygbh")String ygbh);
    int getUserByYgbhUpdate(SysUser user);

    int getSysUserNextID();

    int ResetPasswd(@Param("id")int user_id, @Param("password")String password);

    int updateBySysUser(SysUser user);

    void updateLoginDefaltNum(@Param("username") String username, @Param("sbcs") int i);

    void updateLoginIPAndDate( @Param("date")Date date,  @Param("ip")String ip,  @Param("loginname")String username);
}