package com.scxd.dao.mapper.test;

import com.scxd.beans.pojo.test.BizDrvInfoBean;

public interface BizDrvInfoBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_DRV_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_DRV_INFO
     *
     * @mbggenerated
     */
    int insert(BizDrvInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_DRV_INFO
     *
     * @mbggenerated
     */
    int insertSelective(BizDrvInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_DRV_INFO
     *
     * @mbggenerated
     */
    BizDrvInfoBean selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_DRV_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizDrvInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_DRV_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizDrvInfoBean record);
}