package com.scxd.dao.mapper.test;

import com.scxd.beans.pojo.test.BizVehInfoBean;

public interface BizVehInfoBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_VEH_INFO
     *
     * @mbggenerated
     */
    int insert(BizVehInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_VEH_INFO
     *
     * @mbggenerated
     */
    int insertSelective(BizVehInfoBean record);
}